services:

  postgres:
    image: postgres:18
    restart: "no"
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 5s

  redis:
    image: redis:8.6-alpine
    restart: "no"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 5s
    ports:
      - "6379:6379"

  prestart:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/app"
      POSTGRES_SERVER: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      REDIS_URL: "redis://redis:6379/0"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: backend/Dockerfile
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command:
      - fastapi
      - run
      - --reload
      - "app/main.py"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
        - path: ./packages/scrape_core
          action: sync
          target: /app/packages/scrape_core
    environment:
      DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/app"
      POSTGRES_SERVER: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      REDIS_URL: "redis://redis:6379/0"

  scrape_worker:
    profiles: ["worker"]
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - backend
    env_file:
      - .env
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./scrape_worker
          action: sync
          target: /app/scrape_worker

  frontend:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL-http://localhost:8000}
        - NODE_ENV=development
