from __future__ import annotations

import argparse
import asyncio
import csv
import json
import logging
import os
import sys
from collections.abc import Iterable, Sequence
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Literal, cast

from kiizama_scrape_core.ig_scraper_v2 import (
    InstagramBatchScrapeRunner,
    build_scraper_v2_config,
    enrich_with_ai_analysis,
    persist_scrape_results_to_db,
)
from kiizama_scrape_core.ig_scraper_v2.schemas import InstagramBatchScrapeResponse
from pydantic import ValidationError
from sqlalchemy.exc import SQLAlchemyError
from sqlmodel import Session, select

from app.core.config import settings
from app.core.db import engine, ping_postgres
from app.features.ig_scraper_v2_runtime import (
    BackendInstagramCredentialsStoreV2,
    BackendInstagramProfileAnalysisServiceV2,
    BackendInstagramScrapePersistenceV2,
)
from app.models import IgProfile
from scripts.validate_ig_v2_login import FilteredInstagramCredentialsStore

EXIT_SUCCESS = 0
EXIT_SCRAPE_FAILED = 1
EXIT_CONFIG_ERROR = 2
EXIT_INTERRUPTED = 130

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = REPO_ROOT / "local_data" / "ig_recommended"

EXPORT_HEADERS = ("username", "updated_at", "status", "processed_at", "error")
RECOMMENDED_HEADERS = (
    "username",
    "source_usernames",
    "status",
    "discovered_at",
    "processed_at",
    "error",
)
ACTIVE_STATUSES = {"pending"}
RETRYABLE_STATUSES = {"pending", "failed"}
NOT_FOUND_ERROR = "Instagram username does not exist"

Mode = Literal["export_profiles", "discover_recommended", "persist_recommended"]


@dataclass(frozen=True, slots=True)
class ScriptOptions:
    mode: Mode
    output_dir: Path
    output_csv: Path | None
    input_csv: Path | None
    recommended_csv: Path | None
    updated_after: datetime | None
    updated_before: datetime | None
    oldest: int | None
    newest: int | None
    batch_size: int
    retry_failed: bool
    headless: bool | None
    use_proxy: bool
    proxy_urls: tuple[str, ...] | None
    timeout_ms: int | None
    credential_id: str | None
    login_username: str | None
    max_concurrent: int
    max_posts: int
    skip_ai: bool
    json_output: bool


@dataclass(frozen=True, slots=True)
class ExportOutput:
    success: bool
    path: str
    exported_count: int
    error: str | None = None


@dataclass(frozen=True, slots=True)
class DiscoverRecommendedOutput:
    success: bool
    input_csv: str
    recommended_csv: str
    discovery_counters: dict[str, int]
    discovered_count: int
    skipped_existing_count: int
    error: str | None = None


@dataclass(frozen=True, slots=True)
class PersistRecommendedOutput:
    success: bool
    recommended_csv: str
    persistence_counters: dict[str, int]
    persisted_usernames: list[str]
    not_found_usernames: list[str]
    failed_usernames: list[str]
    error: str | None = None


RunOutput = ExportOutput | DiscoverRecommendedOutput | PersistRecommendedOutput


def parse_args(argv: list[str] | None = None) -> ScriptOptions:
    parser = argparse.ArgumentParser(
        description="Export IG profile usernames and scrape recommended profiles."
    )
    mode_group = parser.add_mutually_exclusive_group(required=True)
    mode_group.add_argument(
        "--export-profiles",
        action="store_true",
        help="Export usernames from private.ig_profiles to a local CSV.",
    )
    mode_group.add_argument(
        "--scrape-recommended",
        action="store_true",
        dest="discover_recommended",
        help=(
            "Read an exported CSV and create/update a recommended_users CSV. "
            "Alias for --discover-recommended."
        ),
    )
    mode_group.add_argument(
        "--discover-recommended",
        action="store_true",
        help="Read an exported CSV and create/update a recommended_users CSV.",
    )
    mode_group.add_argument(
        "--persist-recommended",
        action="store_true",
        help="Read a recommended_users CSV, scrape those usernames, and persist them.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for generated CSV files.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help="CSV path for --export-profiles output.",
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=None,
        help="CSV generated by --export-profiles.",
    )
    parser.add_argument(
        "--recommended-csv",
        type=Path,
        default=None,
        help="CSV path for discovered recommended usernames.",
    )
    parser.add_argument(
        "--updated-after",
        type=parse_datetime_arg,
        default=None,
        help="Only export profiles updated at or after this ISO datetime.",
    )
    parser.add_argument(
        "--updated-before",
        type=parse_datetime_arg,
        default=None,
        help="Only export profiles updated at or before this ISO datetime.",
    )
    oldest_newest_group = parser.add_mutually_exclusive_group()
    oldest_newest_group.add_argument(
        "--oldest",
        type=positive_int,
        default=None,
        metavar="N",
        help="Export the N oldest profiles by updated_at.",
    )
    oldest_newest_group.add_argument(
        "--newest",
        type=positive_int,
        default=None,
        metavar="N",
        help="Export the N newest profiles by updated_at.",
    )
    parser.add_argument(
        "--batch-size",
        type=positive_int,
        default=50,
        help="Number of usernames to process per batch in scrape mode.",
    )
    parser.add_argument(
        "--retry-failed",
        action="store_true",
        help="Retry rows currently marked failed in either CSV.",
    )

    headless_group = parser.add_mutually_exclusive_group()
    headless_group.add_argument(
        "--headed",
        action="store_true",
        help="Run Chromium in headed mode.",
    )
    headless_group.add_argument(
        "--headless",
        action="store_true",
        help="Run Chromium in headless mode.",
    )
    parser.add_argument(
        "--use-proxy",
        action="store_true",
        help="Enable ISP/DECODO proxy mode.",
    )
    parser.add_argument(
        "--proxy-url",
        action="append",
        default=None,
        help="Proxy URL for DECODO/ISP mode. Can be passed multiple times.",
    )
    parser.add_argument(
        "--timeout-ms",
        type=positive_int,
        default=None,
        help="Playwright navigation timeout in milliseconds.",
    )
    parser.add_argument(
        "--credential-id",
        default=None,
        help="Scrape with a specific private.ig_credentials id.",
    )
    parser.add_argument(
        "--login-username",
        default=None,
        help="Scrape with a specific Instagram login username.",
    )
    parser.add_argument(
        "--max-concurrent",
        type=positive_int,
        default=5,
        help="Maximum concurrent profile pages.",
    )
    parser.add_argument(
        "--max-posts",
        type=positive_int,
        default=12,
        help="Maximum posts and reels to collect per profile.",
    )
    parser.add_argument(
        "--skip-ai",
        action="store_true",
        help="Skip AI enrichment while persisting recommended profiles.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print machine-readable JSON to stdout.",
    )

    args = parser.parse_args(argv)
    if args.discover_recommended and args.input_csv is None:
        parser.error("--discover-recommended requires --input-csv.")
    if args.persist_recommended and args.recommended_csv is None:
        parser.error("--persist-recommended requires --recommended-csv.")
    if args.export_profiles and args.input_csv is not None:
        parser.error("--input-csv is only valid with --discover-recommended.")
    if args.export_profiles and args.recommended_csv is not None:
        parser.error("--recommended-csv is only valid with recommended modes.")

    headless: bool | None = None
    if args.headed:
        headless = False
    elif args.headless:
        headless = True

    mode: Mode = "export_profiles"
    if args.discover_recommended:
        mode = "discover_recommended"
    elif args.persist_recommended:
        mode = "persist_recommended"

    return ScriptOptions(
        mode=mode,
        output_dir=args.output_dir,
        output_csv=args.output_csv,
        input_csv=args.input_csv,
        recommended_csv=args.recommended_csv,
        updated_after=args.updated_after,
        updated_before=args.updated_before,
        oldest=args.oldest,
        newest=args.newest,
        batch_size=args.batch_size,
        retry_failed=args.retry_failed,
        headless=headless,
        use_proxy=args.use_proxy,
        proxy_urls=tuple(args.proxy_url) if args.proxy_url else None,
        timeout_ms=args.timeout_ms,
        credential_id=args.credential_id,
        login_username=args.login_username,
        max_concurrent=args.max_concurrent,
        max_posts=args.max_posts,
        skip_ai=args.skip_ai,
        json_output=args.json,
    )


def positive_int(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("must be a valid integer") from exc
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return parsed


def parse_datetime_arg(value: str) -> datetime:
    normalized = value.strip()
    if normalized.endswith("Z"):
        normalized = f"{normalized[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("must be a valid ISO datetime") from exc
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=UTC)
    return parsed.astimezone(UTC)


def utcnow() -> datetime:
    return datetime.now(UTC)


def timestamp_for_filename(now: datetime | None = None) -> str:
    current = now or utcnow()
    return current.astimezone(UTC).strftime("%Y%m%dT%H%M%SZ")


def configure_runtime_secrets_from_settings() -> None:
    os.environ.setdefault(
        "SECRET_KEY_IG_CREDENTIALS",
        settings.SECRET_KEY_IG_CREDENTIALS,
    )
    if settings.OPENAI_API_KEY:
        os.environ.setdefault("OPENAI_API_KEY", settings.OPENAI_API_KEY)


def build_config_from_options(options: ScriptOptions):
    return build_scraper_v2_config(
        headless=options.headless,
        timeout_ms=options.timeout_ms,
        max_concurrent=options.max_concurrent,
        max_posts=options.max_posts,
        use_isp_proxy=options.use_proxy,
        proxy_urls=options.proxy_urls,
    )


def build_credentials_store(options: ScriptOptions):
    base_store = BackendInstagramCredentialsStoreV2(lambda: Session(engine))
    return FilteredInstagramCredentialsStore(
        base_store,
        credential_id=options.credential_id,
        login_username=options.login_username,
    )


def build_persistence(session: Session) -> BackendInstagramScrapePersistenceV2:
    return BackendInstagramScrapePersistenceV2(
        profiles_collection=session,
        posts_collection=session,
        reels_collection=session,
        metrics_collection=session,
        snapshots_collection=session,
    )


def resolve_export_csv_path(options: ScriptOptions) -> Path:
    if options.output_csv is not None:
        return options.output_csv
    return options.output_dir / f"profiles_{timestamp_for_filename()}.csv"


def resolve_recommended_csv_path(options: ScriptOptions) -> Path:
    if options.recommended_csv is not None:
        return options.recommended_csv
    return options.output_dir / f"recommended_{timestamp_for_filename()}.csv"


def ensure_parent_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def normalize_username(value: str | None) -> str:
    return (value or "").strip().strip("@").strip("/").lower()


def normalize_sources(value: str | None) -> list[str]:
    sources: list[str] = []
    seen: set[str] = set()
    for raw_source in (value or "").split("|"):
        source = normalize_username(raw_source)
        if not source or source in seen:
            continue
        seen.add(source)
        sources.append(source)
    return sources


def join_sources(sources: Iterable[str]) -> str:
    normalized = []
    seen: set[str] = set()
    for source in sources:
        username = normalize_username(source)
        if not username or username in seen:
            continue
        seen.add(username)
        normalized.append(username)
    return "|".join(normalized)


def chunked(items: Sequence[str], size: int) -> Iterable[list[str]]:
    for start in range(0, len(items), size):
        yield list(items[start : start + size])


def row_is_processable(row: dict[str, str], *, retry_failed: bool) -> bool:
    statuses = RETRYABLE_STATUSES if retry_failed else ACTIVE_STATUSES
    return row.get("status", "pending") in statuses


def load_csv_rows(path: Path, headers: Sequence[str]) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        rows: list[dict[str, str]] = []
        for raw_row in reader:
            row = {header: (raw_row.get(header) or "") for header in headers}
            rows.append(row)
        return rows


def write_csv_rows(
    path: Path,
    headers: Sequence[str],
    rows: Sequence[dict[str, str]],
) -> None:
    ensure_parent_dir(path)
    with NamedTemporaryFile(
        "w",
        newline="",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        delete=False,
    ) as temp_file:
        writer = csv.DictWriter(temp_file, fieldnames=list(headers))
        writer.writeheader()
        for row in rows:
            writer.writerow({header: row.get(header, "") for header in headers})
        temp_path = Path(temp_file.name)
    temp_path.replace(path)


def upsert_recommended_rows(
    rows: list[dict[str, str]],
    *,
    source_username: str,
    recommended_usernames: Iterable[str],
    discovered_at: str,
) -> int:
    by_username = {
        normalize_username(row.get("username")): row
        for row in rows
        if normalize_username(row.get("username"))
    }
    added_count = 0
    source = normalize_username(source_username)

    for raw_username in recommended_usernames:
        username = normalize_username(raw_username)
        if not username:
            continue
        existing = by_username.get(username)
        if existing is None:
            row = {
                "username": username,
                "source_usernames": source,
                "status": "pending",
                "discovered_at": discovered_at,
                "processed_at": "",
                "error": "",
            }
            rows.append(row)
            by_username[username] = row
            added_count += 1
            continue

        sources = normalize_sources(existing.get("source_usernames"))
        if source and source not in sources:
            sources.append(source)
            existing["source_usernames"] = join_sources(sources)
        if not existing.get("discovered_at"):
            existing["discovered_at"] = discovered_at
        if not existing.get("status"):
            existing["status"] = "pending"

    return added_count


def get_existing_profile_usernames(usernames: Iterable[str]) -> set[str]:
    normalized_usernames = sorted(
        {normalize_username(username) for username in usernames if username}
    )
    if not normalized_usernames:
        return set()

    username_column = cast(Any, IgProfile.username)
    with Session(engine) as session:
        existing = session.exec(
            select(IgProfile.username).where(username_column.in_(normalized_usernames))
        ).all()
    return {normalize_username(username) for username in existing}


def build_export_statement(options: ScriptOptions) -> Any:
    updated_at = cast(Any, IgProfile.updated_at)
    username = cast(Any, IgProfile.username)
    statement = select(IgProfile.username, IgProfile.updated_at)

    if options.updated_after is not None:
        statement = statement.where(updated_at >= options.updated_after)
    if options.updated_before is not None:
        statement = statement.where(updated_at <= options.updated_before)

    if options.oldest is not None:
        statement = statement.order_by(updated_at.asc(), username.asc()).limit(
            options.oldest
        )
    elif options.newest is not None:
        statement = statement.order_by(updated_at.desc(), username.asc()).limit(
            options.newest
        )
    else:
        statement = statement.order_by(username.asc())
    return statement


def export_profiles_to_csv(options: ScriptOptions) -> ExportOutput:
    output_path = resolve_export_csv_path(options)
    ensure_parent_dir(output_path)
    ping_postgres()

    with Session(engine) as session:
        records = session.exec(build_export_statement(options)).all()

    rows = [
        {
            "username": normalize_username(record[0]),
            "updated_at": record[1].astimezone(UTC).isoformat()
            if record[1].tzinfo
            else record[1].replace(tzinfo=UTC).isoformat(),
            "status": "pending",
            "processed_at": "",
            "error": "",
        }
        for record in records
        if normalize_username(record[0])
    ]
    write_csv_rows(output_path, EXPORT_HEADERS, rows)
    return ExportOutput(
        success=True,
        path=str(output_path),
        exported_count=len(rows),
    )


async def run_runner_response(
    *,
    options: ScriptOptions,
    usernames: list[str],
) -> InstagramBatchScrapeResponse:
    config = build_config_from_options(options)
    return await InstagramBatchScrapeRunner(
        config=config,
        credentials_store=build_credentials_store(options),
        usernames=usernames,
        max_posts=options.max_posts,
    ).run_response()


async def run_discovery_phase(
    *,
    options: ScriptOptions,
    export_rows: list[dict[str, str]],
    export_csv_path: Path,
    recommended_rows: list[dict[str, str]],
    recommended_csv_path: Path,
) -> dict[str, int]:
    counters = {
        "requested": 0,
        "successful": 0,
        "failed": 0,
        "not_found": 0,
        "skipped_existing": 0,
        "added_recommended": 0,
    }
    pending_usernames = [
        normalize_username(row.get("username"))
        for row in export_rows
        if row_is_processable(row, retry_failed=options.retry_failed)
        and normalize_username(row.get("username"))
    ]
    row_by_username = {
        normalize_username(row.get("username")): row
        for row in export_rows
        if normalize_username(row.get("username"))
    }

    for batch in chunked(pending_usernames, options.batch_size):
        counters["requested"] += len(batch)
        response = await run_runner_response(options=options, usernames=batch)
        processed_at = utcnow().isoformat()
        recommended_candidates = [
            normalize_username(user.username)
            for username in batch
            if (result := response.results.get(username)) is not None and result.success
            for user in result.recommended_users
            if normalize_username(user.username)
        ]
        existing_profile_usernames = get_existing_profile_usernames(
            recommended_candidates
        )
        counters["skipped_existing"] += len(existing_profile_usernames)

        for username in batch:
            row = row_by_username[username]
            result = response.results.get(username)
            if result is None:
                row["status"] = "failed"
                row["processed_at"] = processed_at
                row["error"] = response.error or "Missing scrape result"
                counters["failed"] += 1
                continue

            row["processed_at"] = processed_at
            if result.success:
                row["status"] = "done"
                row["error"] = ""
                counters["successful"] += 1
                counters["added_recommended"] += upsert_recommended_rows(
                    recommended_rows,
                    source_username=username,
                    recommended_usernames=[
                        user.username or ""
                        for user in result.recommended_users
                        if normalize_username(user.username)
                        not in existing_profile_usernames
                    ],
                    discovered_at=processed_at,
                )
            elif result.error == NOT_FOUND_ERROR:
                row["status"] = "not_found"
                row["error"] = result.error or ""
                counters["not_found"] += 1
            else:
                row["status"] = "failed"
                row["error"] = result.error or response.error or "Scrape failed"
                counters["failed"] += 1

        write_csv_rows(export_csv_path, EXPORT_HEADERS, export_rows)
        write_csv_rows(recommended_csv_path, RECOMMENDED_HEADERS, recommended_rows)

    return counters


async def run_persistence_phase(
    *,
    options: ScriptOptions,
    recommended_rows: list[dict[str, str]],
    recommended_csv_path: Path,
) -> tuple[dict[str, int], list[str], list[str], list[str]]:
    counters = {"requested": 0, "successful": 0, "failed": 0, "not_found": 0}
    persisted_usernames: list[str] = []
    not_found_usernames: list[str] = []
    failed_usernames: list[str] = []
    pending_usernames = [
        normalize_username(row.get("username"))
        for row in recommended_rows
        if row_is_processable(row, retry_failed=options.retry_failed)
        and normalize_username(row.get("username"))
    ]
    row_by_username = {
        normalize_username(row.get("username")): row
        for row in recommended_rows
        if normalize_username(row.get("username"))
    }

    for batch in chunked(pending_usernames, options.batch_size):
        counters["requested"] += len(batch)
        response = await run_runner_response(options=options, usernames=batch)
        if not options.skip_ai:
            response = await enrich_with_ai_analysis(
                response,
                analysis_service=BackendInstagramProfileAnalysisServiceV2(),
            )

        with Session(engine) as session:
            response = await persist_scrape_results_to_db(
                response,
                persistence=build_persistence(session),
            )

        processed_at = utcnow().isoformat()
        for username in batch:
            row = row_by_username[username]
            result = response.results.get(username)
            row["processed_at"] = processed_at
            if result is None:
                row["status"] = "failed"
                row["error"] = response.error or "Missing scrape result"
                failed_usernames.append(username)
                counters["failed"] += 1
                continue

            if result.success:
                row["status"] = "done"
                row["error"] = ""
                persisted_usernames.append(username)
                counters["successful"] += 1
            elif result.error == NOT_FOUND_ERROR:
                row["status"] = "not_found"
                row["error"] = result.error or ""
                not_found_usernames.append(username)
                counters["not_found"] += 1
            else:
                row["status"] = "failed"
                row["error"] = result.error or response.error or "Scrape failed"
                failed_usernames.append(username)
                counters["failed"] += 1

        write_csv_rows(recommended_csv_path, RECOMMENDED_HEADERS, recommended_rows)

    return counters, persisted_usernames, not_found_usernames, failed_usernames


async def discover_recommended(options: ScriptOptions) -> DiscoverRecommendedOutput:
    if options.input_csv is None:
        raise ValueError("--input-csv is required for --discover-recommended.")

    configure_runtime_secrets_from_settings()
    ping_postgres()

    input_csv_path = options.input_csv
    recommended_csv_path = resolve_recommended_csv_path(options)
    ensure_parent_dir(recommended_csv_path)
    if not input_csv_path.exists():
        raise FileNotFoundError(f"Input CSV not found: {input_csv_path}")

    export_rows = load_csv_rows(input_csv_path, EXPORT_HEADERS)
    recommended_rows = load_csv_rows(recommended_csv_path, RECOMMENDED_HEADERS)
    if not recommended_csv_path.exists():
        write_csv_rows(recommended_csv_path, RECOMMENDED_HEADERS, recommended_rows)

    discovery_counters = await run_discovery_phase(
        options=options,
        export_rows=export_rows,
        export_csv_path=input_csv_path,
        recommended_rows=recommended_rows,
        recommended_csv_path=recommended_csv_path,
    )

    return DiscoverRecommendedOutput(
        success=discovery_counters["failed"] == 0,
        input_csv=str(input_csv_path),
        recommended_csv=str(recommended_csv_path),
        discovery_counters=discovery_counters,
        discovered_count=len(recommended_rows),
        skipped_existing_count=discovery_counters["skipped_existing"],
        error=None,
    )


async def persist_recommended(options: ScriptOptions) -> PersistRecommendedOutput:
    if options.recommended_csv is None:
        raise ValueError("--recommended-csv is required for --persist-recommended.")

    configure_runtime_secrets_from_settings()
    ping_postgres()

    recommended_csv_path = options.recommended_csv
    if not recommended_csv_path.exists():
        raise FileNotFoundError(f"Recommended CSV not found: {recommended_csv_path}")

    recommended_rows = load_csv_rows(recommended_csv_path, RECOMMENDED_HEADERS)
    (
        persistence_counters,
        persisted_usernames,
        not_found_usernames,
        failed_usernames,
    ) = await run_persistence_phase(
        options=options,
        recommended_rows=recommended_rows,
        recommended_csv_path=recommended_csv_path,
    )

    return PersistRecommendedOutput(
        success=persistence_counters["failed"] == 0,
        recommended_csv=str(recommended_csv_path),
        persistence_counters=persistence_counters,
        persisted_usernames=persisted_usernames,
        not_found_usernames=not_found_usernames,
        failed_usernames=failed_usernames,
        error=None,
    )


async def run(options: ScriptOptions) -> RunOutput:
    if options.mode == "export_profiles":
        return export_profiles_to_csv(options)
    if options.mode == "discover_recommended":
        return await discover_recommended(options)
    return await persist_recommended(options)


def print_output(output: RunOutput, *, json_output: bool) -> None:
    payload = asdict(output)
    if json_output:
        sys.stdout.write(f"{json.dumps(payload, sort_keys=True)}\n")
        return

    for key, value in payload.items():
        sys.stdout.write(f"{key}: {value}\n")


def _is_config_error(exc: Exception) -> bool:
    return isinstance(
        exc,
        (
            FileNotFoundError,
            ValueError,
            ValidationError,
            SQLAlchemyError,
            RuntimeError,
        ),
    )


def _json_requested(argv: list[str] | None) -> bool:
    args = argv if argv is not None else sys.argv[1:]
    return "--json" in args


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, stream=sys.stderr)
    try:
        options = parse_args(argv)
        output = asyncio.run(run(options))
        print_output(output, json_output=options.json_output)
        return EXIT_SUCCESS if output.success else EXIT_SCRAPE_FAILED
    except KeyboardInterrupt:
        return EXIT_INTERRUPTED
    except SystemExit:
        raise
    except Exception as exc:
        if _is_config_error(exc):
            output = ExportOutput(
                success=False,
                path="",
                exported_count=0,
                error=str(exc),
            )
            print_output(output, json_output=_json_requested(argv))
            return EXIT_CONFIG_ERROR
        raise


if __name__ == "__main__":
    raise SystemExit(main())
