// This file is auto-generated by @hey-api/openapi-ts

export const BioLinkSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['title', 'url'],
    title: 'BioLink'
} as const;

export const Body_internal_login_login_internal_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_internal-login-login_internal_access_token'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CreatorsSearchHistoryCreateRequestSchema = {
    properties: {
        source: {
            type: 'string',
            enum: ['direct-search', 'ig-scrape-job'],
            title: 'Source'
        },
        job_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Id'
        },
        ready_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 50,
            minItems: 1,
            title: 'Ready Usernames'
        }
    },
    type: 'object',
    required: ['source', 'ready_usernames'],
    title: 'CreatorsSearchHistoryCreateRequest'
} as const;

export const CreatorsSearchHistoryItemSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        source: {
            type: 'string',
            enum: ['direct-search', 'ig-scrape-job'],
            title: 'Source'
        },
        job_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Id'
        },
        ready_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Ready Usernames'
        }
    },
    type: 'object',
    required: ['id', 'created_at', 'source'],
    title: 'CreatorsSearchHistoryItem'
} as const;

export const CreatorsSearchHistoryListResponseSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/CreatorsSearchHistoryItem'
            },
            type: 'array',
            title: 'Items'
        },
        count: {
            type: 'integer',
            title: 'Count',
            default: 0
        }
    },
    type: 'object',
    title: 'CreatorsSearchHistoryListResponse'
} as const;

export const FeatureFlagAuditPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        feature_flag_key: {
            type: 'string',
            title: 'Feature Flag Key'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        old_is_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Old Is Enabled'
        },
        new_is_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'New Is Enabled'
        },
        old_is_public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Old Is Public'
        },
        new_is_public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'New Is Public'
        },
        changed_by_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed By Email'
        },
        changed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Changed At'
        }
    },
    type: 'object',
    required: ['id', 'feature_flag_key', 'action', 'changed_at'],
    title: 'FeatureFlagAuditPublic'
} as const;

export const FeatureFlagAuditsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FeatureFlagAuditPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FeatureFlagAuditsPublic'
} as const;

export const FeatureFlagCreateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Key'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled',
            default: false
        },
        is_public: {
            type: 'boolean',
            title: 'Is Public',
            default: false
        }
    },
    type: 'object',
    required: ['key'],
    title: 'FeatureFlagCreate'
} as const;

export const FeatureFlagPublicSchema = {
    properties: {
        key: {
            type: 'string',
            title: 'Key'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled'
        },
        is_public: {
            type: 'boolean',
            title: 'Is Public'
        }
    },
    type: 'object',
    required: ['key', 'is_enabled', 'is_public'],
    title: 'FeatureFlagPublic'
} as const;

export const FeatureFlagUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Enabled'
        },
        is_public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Public'
        }
    },
    type: 'object',
    title: 'FeatureFlagUpdate'
} as const;

export const FeatureFlagsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FeatureFlagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FeatureFlagsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const IgCredentialSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        login_username: {
            type: 'string',
            minLength: 1,
            title: 'Login Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        session: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session'
        }
    },
    type: 'object',
    required: ['login_username', 'password'],
    title: 'IgCredential',
    description: 'Container for a single Instagram credential record.',
    example: {
        id: '65c2f0b7f6b7a8c1c3d4e5fa',
        login_username: 'user@example.com',
        password: 'my_plain_password',
        session: {
            cookies: [
                {
                    domain: '.instagram.com',
                    name: 'sessionid',
                    value: 'abcd'
                }
            ]
        }
    }
} as const;

export const IgCredentialPublicSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        login_username: {
            type: 'string',
            minLength: 1,
            title: 'Login Username'
        },
        session: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session'
        }
    },
    type: 'object',
    required: ['login_username'],
    title: 'IgCredentialPublic',
    description: 'Public view of a single Instagram credential record.',
    example: {
        id: '65c2f0b7f6b7a8c1c3d4e5fa',
        login_username: 'user@example.com',
        session: {
            cookies: [
                {
                    domain: '.instagram.com',
                    name: 'sessionid',
                    value: 'abcd'
                }
            ]
        }
    }
} as const;

export const IgCredentialPublicCollectionSchema = {
    properties: {
        ig_credentials: {
            items: {
                '$ref': '#/components/schemas/IgCredentialPublic'
            },
            type: 'array',
            title: 'Ig Credentials'
        }
    },
    type: 'object',
    required: ['ig_credentials'],
    title: 'IgCredentialPublicCollection',
    description: 'A container holding a list of `IgCredentialPublic` instances.'
} as const;

export const InstagramAIRequestSchema = {
    properties: {
        profiles: {
            items: {
                '$ref': '#/components/schemas/InstagramProfileInput'
            },
            type: 'array',
            title: 'Profiles'
        }
    },
    type: 'object',
    required: ['profiles'],
    title: 'InstagramAIRequest',
    description: 'Payload for testing the Instagram OpenAI classifier.'
} as const;

export const InstagramAIResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/InstagramAIResult'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'InstagramAIResponse'
} as const;

export const InstagramAIResultSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        categories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Categories'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        }
    },
    type: 'object',
    required: ['username', 'categories', 'roles'],
    title: 'InstagramAIResult'
} as const;

export const InstagramBatchCountersSchemaSchema = {
    properties: {
        requested: {
            type: 'integer',
            title: 'Requested',
            default: 0
        },
        successful: {
            type: 'integer',
            title: 'Successful',
            default: 0
        },
        failed: {
            type: 'integer',
            title: 'Failed',
            default: 0
        },
        not_found: {
            type: 'integer',
            title: 'Not Found',
            default: 0
        }
    },
    type: 'object',
    title: 'InstagramBatchCountersSchema'
} as const;

export const InstagramBatchRecommendationsRequestSchema = {
    properties: {
        usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 10,
            minItems: 1,
            title: 'Usernames'
        },
        timeout_ms: {
            type: 'integer',
            title: 'Timeout Ms',
            default: 30000
        },
        headless: {
            type: 'boolean',
            title: 'Headless',
            default: true
        },
        user_agent: {
            type: 'string',
            title: 'User Agent',
            default: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'
        },
        locale: {
            type: 'string',
            title: 'Locale',
            default: 'en-US'
        },
        max_posts: {
            type: 'integer',
            title: 'Max Posts',
            default: 12
        },
        max_concurrent: {
            type: 'integer',
            minimum: 1,
            title: 'Max Concurrent'
        },
        measure_network_bytes: {
            type: 'boolean',
            title: 'Measure Network Bytes',
            description: 'When true, tracks total downloaded bytes from Playwright responses (session validation + scraping).',
            default: false
        },
        proxy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxy'
        },
        recommended_limit: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Recommended Limit',
            description: 'Maximum recommended users returned per profile.',
            default: 10
        }
    },
    type: 'object',
    required: ['usernames'],
    title: 'InstagramBatchRecommendationsRequest'
} as const;

export const InstagramBatchRecommendationsResponseSchema = {
    properties: {
        usernames: {
            items: {
                '$ref': '#/components/schemas/InstagramBatchUsernameStatus'
            },
            type: 'array',
            title: 'Usernames'
        },
        recommendations: {
            additionalProperties: {
                items: {
                    '$ref': '#/components/schemas/InstagramSuggestedUserSchema'
                },
                type: 'array'
            },
            type: 'object',
            title: 'Recommendations'
        },
        counters: {
            '$ref': '#/components/schemas/InstagramBatchCountersSchema'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    title: 'InstagramBatchRecommendationsResponse'
} as const;

export const InstagramBatchScrapeRequestSchema = {
    properties: {
        usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 10,
            minItems: 1,
            title: 'Usernames'
        },
        timeout_ms: {
            type: 'integer',
            title: 'Timeout Ms',
            default: 30000
        },
        headless: {
            type: 'boolean',
            title: 'Headless',
            default: true
        },
        user_agent: {
            type: 'string',
            title: 'User Agent',
            default: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'
        },
        locale: {
            type: 'string',
            title: 'Locale',
            default: 'en-US'
        },
        max_posts: {
            type: 'integer',
            title: 'Max Posts',
            default: 12
        },
        max_concurrent: {
            type: 'integer',
            minimum: 1,
            title: 'Max Concurrent'
        },
        measure_network_bytes: {
            type: 'boolean',
            title: 'Measure Network Bytes',
            description: 'When true, tracks total downloaded bytes from Playwright responses (session validation + scraping).',
            default: false
        },
        proxy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxy'
        }
    },
    type: 'object',
    required: ['usernames'],
    title: 'InstagramBatchScrapeRequest'
} as const;

export const InstagramBatchScrapeSummaryResponseSchema = {
    properties: {
        usernames: {
            items: {
                '$ref': '#/components/schemas/InstagramBatchUsernameStatus'
            },
            type: 'array',
            title: 'Usernames'
        },
        counters: {
            '$ref': '#/components/schemas/InstagramBatchCountersSchema'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    title: 'InstagramBatchScrapeSummaryResponse'
} as const;

export const InstagramBatchUsernameStatusSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        status: {
            type: 'string',
            enum: ['success', 'failed', 'skipped', 'not_found'],
            title: 'Status'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['username', 'status'],
    title: 'InstagramBatchUsernameStatus'
} as const;

export const InstagramPostSchemaSchema = {
    properties: {
        code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code'
        },
        caption_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caption Text'
        },
        is_paid_partnership: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Paid Partnership'
        },
        sponsor_tags: {
            title: 'Sponsor Tags'
        },
        coauthor_producers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Coauthor Producers'
        },
        comment_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment Count'
        },
        like_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Like Count'
        },
        usertags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Usertags'
        },
        timestamp: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timestamp'
        },
        media_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        product_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        }
    },
    type: 'object',
    title: 'InstagramPostSchema'
} as const;

export const InstagramProfileInputSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        follower_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Follower Count'
        },
        posts: {
            items: {
                '$ref': '#/components/schemas/InstagramPostSchema'
            },
            type: 'array',
            title: 'Posts'
        }
    },
    type: 'object',
    required: ['username'],
    title: 'InstagramProfileInput'
} as const;

export const InstagramReportRequestSchema = {
    properties: {
        usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 20,
            minItems: 1,
            title: 'Usernames',
            description: 'Lista de usernames a usar para generar los reportes (max 20).'
        },
        template_name: {
            type: 'string',
            title: 'Template Name',
            description: 'Nombre de la plantilla a renderizar.',
            default: 'social_media_report.html'
        },
        generate_html: {
            type: 'boolean',
            title: 'Generate Html',
            description: 'Indica si debe generarse el HTML como parte del proceso.',
            default: true
        },
        generate_pdf: {
            type: 'boolean',
            title: 'Generate Pdf',
            description: 'Indica si debe generarse un PDF a partir del HTML.',
            default: false
        }
    },
    type: 'object',
    required: ['usernames'],
    title: 'InstagramReportRequest',
    description: 'Payload para generar reportes de Instagram.'
} as const;

export const InstagramScrapeJobCreateRequestSchema = {
    properties: {
        usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 10,
            minItems: 1,
            title: 'Usernames'
        },
        timeout_ms: {
            type: 'integer',
            title: 'Timeout Ms',
            default: 30000
        },
        headless: {
            type: 'boolean',
            title: 'Headless',
            default: true
        },
        user_agent: {
            type: 'string',
            title: 'User Agent',
            default: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'
        },
        locale: {
            type: 'string',
            title: 'Locale',
            default: 'en-US'
        },
        max_posts: {
            type: 'integer',
            title: 'Max Posts',
            default: 12
        },
        max_concurrent: {
            type: 'integer',
            minimum: 1,
            title: 'Max Concurrent'
        },
        measure_network_bytes: {
            type: 'boolean',
            title: 'Measure Network Bytes',
            description: 'When true, tracks total downloaded bytes from Playwright responses (session validation + scraping).',
            default: false
        },
        proxy: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Proxy'
        }
    },
    type: 'object',
    required: ['usernames'],
    title: 'InstagramScrapeJobCreateRequest'
} as const;

export const InstagramScrapeJobCreateResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            const: 'queued',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['job_id', 'status'],
    title: 'InstagramScrapeJobCreateResponse'
} as const;

export const InstagramScrapeJobReferencesSchema = {
    properties: {
        all_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'All Usernames'
        },
        successful_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Successful Usernames'
        },
        failed_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Failed Usernames'
        },
        skipped_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Skipped Usernames'
        },
        not_found_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Not Found Usernames'
        }
    },
    type: 'object',
    title: 'InstagramScrapeJobReferences'
} as const;

export const InstagramScrapeJobStatusResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        status: {
            type: 'string',
            enum: ['queued', 'running', 'done', 'failed'],
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        },
        attempts: {
            type: 'integer',
            title: 'Attempts',
            default: 0
        },
        lease_owner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lease Owner'
        },
        leased_until: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Leased Until'
        },
        heartbeat_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Heartbeat At'
        },
        summary: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InstagramBatchScrapeSummaryResponse'
                },
                {
                    type: 'null'
                }
            ]
        },
        references: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InstagramScrapeJobReferences'
                },
                {
                    type: 'null'
                }
            ]
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['job_id', 'status', 'created_at', 'updated_at', 'expires_at'],
    title: 'InstagramScrapeJobStatusResponse'
} as const;

export const InstagramScrapeJobTerminalizationRequestSchema = {
    properties: {
        status: {
            type: 'string',
            enum: ['done', 'failed'],
            title: 'Status'
        },
        attempt: {
            type: 'integer',
            minimum: 1,
            title: 'Attempt'
        },
        worker_id: {
            type: 'string',
            minLength: 1,
            title: 'Worker Id'
        },
        completed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Completed At'
        },
        summary: {
            '$ref': '#/components/schemas/InstagramBatchScrapeSummaryResponse'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        }
    },
    type: 'object',
    required: ['status', 'attempt', 'worker_id', 'completed_at', 'summary'],
    title: 'InstagramScrapeJobTerminalizationRequest'
} as const;

export const InstagramScrapeJobTerminalizationResponseSchema = {
    properties: {
        job_id: {
            type: 'string',
            title: 'Job Id'
        },
        decision: {
            type: 'string',
            enum: ['accepted_new', 'accepted_pending', 'duplicate', 'conflict'],
            title: 'Decision'
        },
        status: {
            type: 'string',
            enum: ['done', 'failed'],
            title: 'Status'
        },
        notification_id: {
            type: 'string',
            minLength: 1,
            title: 'Notification Id'
        },
        terminal_event_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Terminal Event Id'
        }
    },
    type: 'object',
    required: ['job_id', 'decision', 'status', 'notification_id'],
    title: 'InstagramScrapeJobTerminalizationResponse'
} as const;

export const InstagramSuggestedUserSchemaSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        profile_pic_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Pic Url'
        }
    },
    type: 'object',
    title: 'InstagramSuggestedUserSchema'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MetricsSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        post_metrics: {
            '$ref': '#/components/schemas/PostMetrics'
        },
        reel_metrics: {
            '$ref': '#/components/schemas/ReelMetrics'
        },
        overall_post_engagement_rate: {
            type: 'number',
            title: 'Overall Post Engagement Rate'
        },
        reel_engagement_rate_on_plays: {
            type: 'number',
            title: 'Reel Engagement Rate On Plays'
        }
    },
    type: 'object',
    required: ['post_metrics', 'reel_metrics', 'overall_post_engagement_rate', 'reel_engagement_rate_on_plays'],
    title: 'Metrics',
    description: 'Container for metrics derived from posts and reels.',
    example: {
        id: '65c2f0b7f6b7a8c1c3d4e5f8',
        overall_post_engagement_rate: 0.5734,
        post_metrics: {
            avg_comments: 718.66,
            avg_engagement_rate: 0.0477,
            avg_likes: 69842,
            hashtags_per_post: 0.16,
            mentions_per_post: 0,
            total_comments: 8624,
            total_likes: 838104,
            total_posts: 12
        },
        reel_engagement_rate_on_plays: 0.1435,
        reel_metrics: {
            avg_plays: 221915.66,
            avg_reel_comments: 390.25,
            avg_reel_likes: 44782.58,
            total_plays: 2662988,
            total_reels: 12
        }
    }
} as const;

export const MetricsCollectionSchema = {
    properties: {
        metrics: {
            items: {
                '$ref': '#/components/schemas/Metrics'
            },
            type: 'array',
            title: 'Metrics'
        }
    },
    type: 'object',
    required: ['metrics'],
    title: 'MetricsCollection',
    description: 'A container holding a list of `Metrics` instances.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 25,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PostItemSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        caption_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Caption Text'
        },
        is_paid_partnership: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Paid Partnership'
        },
        coauthor_producers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Coauthor Producers'
        },
        comment_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment Count'
        },
        like_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Like Count'
        },
        usertags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Usertags'
        },
        media_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        product_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'PostItem',
    description: 'Single post payload stored inside a PostsDocument.'
} as const;

export const PostMetricsSchema = {
    properties: {
        total_posts: {
            type: 'integer',
            title: 'Total Posts'
        },
        total_likes: {
            type: 'integer',
            title: 'Total Likes'
        },
        total_comments: {
            type: 'integer',
            title: 'Total Comments'
        },
        avg_likes: {
            type: 'number',
            title: 'Avg Likes'
        },
        avg_comments: {
            type: 'number',
            title: 'Avg Comments'
        },
        avg_engagement_rate: {
            type: 'number',
            title: 'Avg Engagement Rate'
        },
        hashtags_per_post: {
            type: 'number',
            title: 'Hashtags Per Post'
        },
        mentions_per_post: {
            type: 'number',
            title: 'Mentions Per Post'
        }
    },
    type: 'object',
    required: ['total_posts', 'total_likes', 'total_comments', 'avg_likes', 'avg_comments', 'avg_engagement_rate', 'hashtags_per_post', 'mentions_per_post'],
    title: 'PostMetrics'
} as const;

export const PostsDocumentSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        profile_id: {
            type: 'string',
            title: 'Profile Id'
        },
        posts: {
            items: {
                '$ref': '#/components/schemas/PostItem'
            },
            type: 'array',
            title: 'Posts'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['profile_id', 'updated_at'],
    title: 'PostsDocument',
    description: 'Container for the latest list of posts for a profile.',
    example: {
        id: '65c2f0b7f6b7a8c1c3d4e5f6',
        posts: [
            {
                caption_text: 'What makes you smile?',
                coauthor_producers: [],
                code: 'CVTH2dLvmkt',
                comment_count: 860,
                is_paid_partnership: false,
                like_count: 141588,
                media_type: 8,
                product_type: 'carousel_container',
                usertags: ['nickthiessen']
            }
        ],
        profile_id: '65c2f0b7f6b7a8c1c3d4e5aa',
        updated_at: '2024-02-12T15:04:05Z'
    }
} as const;

export const PostsDocumentCollectionSchema = {
    properties: {
        posts: {
            items: {
                '$ref': '#/components/schemas/PostsDocument'
            },
            type: 'array',
            title: 'Posts'
        }
    },
    type: 'object',
    required: ['posts'],
    title: 'PostsDocumentCollection',
    description: 'A container holding a list of `PostsDocument` instances.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 25,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProfileSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        ig_id: {
            type: 'string',
            title: 'Ig Id'
        },
        username: {
            type: 'string',
            minLength: 1,
            title: 'Username'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        biography: {
            type: 'string',
            title: 'Biography'
        },
        is_private: {
            type: 'boolean',
            title: 'Is Private'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified'
        },
        profile_pic_url: {
            type: 'string',
            minLength: 1,
            format: 'uri',
            title: 'Profile Pic Url'
        },
        profile_pic_src: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Pic Src'
        },
        external_url: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1,
                    format: 'uri'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Url'
        },
        updated_date: {
            type: 'string',
            format: 'date-time',
            title: 'Updated Date'
        },
        follower_count: {
            type: 'integer',
            title: 'Follower Count'
        },
        following_count: {
            type: 'integer',
            title: 'Following Count'
        },
        media_count: {
            type: 'integer',
            title: 'Media Count'
        },
        bio_links: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/BioLink'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio Links'
        },
        ai_categories: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Categories'
        },
        ai_roles: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Roles'
        }
    },
    type: 'object',
    required: ['ig_id', 'username', 'full_name', 'biography', 'is_private', 'is_verified', 'profile_pic_url', 'updated_date', 'follower_count', 'following_count', 'media_count'],
    title: 'Profile',
    description: 'Container for a single profile record.',
    example: {
        ai_categories: ['Motherhood / Family / Parenting', 'Gaming / Esports / Streaming'],
        ai_roles: ['Aspirational / Lifestyle', 'Entertainment'],
        bio_links: [
            {
                title: 'Twitch',
                url: 'http://twitch.tv/stpeach'
            },
            {
                title: 'YouTube',
                url: 'http://youtube.com/stpeach'
            }
        ],
        biography: 'Fitness & lifestyle creator. Links below 👇',
        external_url: 'https://twitch.tv/stpeach',
        follower_count: 1200000,
        following_count: 350,
        full_name: 'STPeach',
        id: '65c2f0b7f6b7a8c1c3d4e5f6',
        ig_id: '1234567890',
        is_private: 'false',
        is_verified: 'true',
        media_count: 2500,
        profile_pic_url: 'https://cdn.example.com/stpeach.jpg',
        updated_date: '2024-02-12T15:04:05Z',
        username: 'stpeach'
    }
} as const;

export const ProfileCollectionSchema = {
    properties: {
        profiles: {
            items: {
                '$ref': '#/components/schemas/Profile'
            },
            type: 'array',
            title: 'Profiles'
        }
    },
    type: 'object',
    required: ['profiles'],
    title: 'ProfileCollection',
    description: 'A container holding a list of `Profile` instances'
} as const;

export const ProfileExistenceCollectionSchema = {
    properties: {
        profiles: {
            items: {
                '$ref': '#/components/schemas/ProfileExistenceItem'
            },
            type: 'array',
            title: 'Profiles'
        }
    },
    type: 'object',
    title: 'ProfileExistenceCollection'
} as const;

export const ProfileExistenceItemSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        exists: {
            type: 'boolean',
            title: 'Exists'
        },
        expired: {
            type: 'boolean',
            title: 'Expired'
        }
    },
    type: 'object',
    required: ['username', 'exists', 'expired'],
    title: 'ProfileExistenceItem'
} as const;

export const ProfileSnapshotSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        profile_id: {
            type: 'string',
            title: 'Profile Id'
        },
        post_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Post Ids'
        },
        reel_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Reel Ids'
        },
        metrics_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metrics Id'
        },
        scraped_at: {
            type: 'string',
            format: 'date-time',
            title: 'Scraped At'
        }
    },
    type: 'object',
    required: ['profile_id', 'scraped_at'],
    title: 'ProfileSnapshot',
    description: 'Relates a profile to scraped posts, reels, and metrics at a point in time.',
    example: {
        id: '65c2f0b7f6b7a8c1c3d4e5f9',
        metrics_id: '65c2f0b7f6b7a8c1c3d4e8c1',
        post_ids: ['65c2f0b7f6b7a8c1c3d4e6a1', '65c2f0b7f6b7a8c1c3d4e6a2'],
        profile_id: '65c2f0b7f6b7a8c1c3d4e5f6',
        reel_ids: ['65c2f0b7f6b7a8c1c3d4e7b1', '65c2f0b7f6b7a8c1c3d4e7b2'],
        scraped_at: '2024-02-12T15:04:05Z'
    }
} as const;

export const ProfileSnapshotCollectionSchema = {
    properties: {
        snapshots: {
            items: {
                '$ref': '#/components/schemas/ProfileSnapshot'
            },
            type: 'array',
            title: 'Snapshots'
        }
    },
    type: 'object',
    required: ['snapshots'],
    title: 'ProfileSnapshotCollection',
    description: 'A container holding a list of `ProfileSnapshot` instances.'
} as const;

export const ProfileSnapshotExpandedSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        profile_id: {
            type: 'string',
            title: 'Profile Id'
        },
        post_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Post Ids'
        },
        reel_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Reel Ids'
        },
        metrics_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metrics Id'
        },
        scraped_at: {
            type: 'string',
            format: 'date-time',
            title: 'Scraped At'
        },
        profile: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Profile'
                },
                {
                    type: 'null'
                }
            ]
        },
        posts: {
            items: {
                '$ref': '#/components/schemas/PostsDocument'
            },
            type: 'array',
            title: 'Posts'
        },
        reels: {
            items: {
                '$ref': '#/components/schemas/ReelsDocument'
            },
            type: 'array',
            title: 'Reels'
        },
        metrics: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Metrics'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['profile_id', 'scraped_at'],
    title: 'ProfileSnapshotExpanded',
    description: 'Profile snapshot with full related data resolved via lookup.',
    example: {
        id: '65c2f0b7f6b7a8c1c3d4e5f9',
        metrics_id: '65c2f0b7f6b7a8c1c3d4e8c1',
        post_ids: ['65c2f0b7f6b7a8c1c3d4e6a1', '65c2f0b7f6b7a8c1c3d4e6a2'],
        profile_id: '65c2f0b7f6b7a8c1c3d4e5f6',
        reel_ids: ['65c2f0b7f6b7a8c1c3d4e7b1', '65c2f0b7f6b7a8c1c3d4e7b2'],
        scraped_at: '2024-02-12T15:04:05Z'
    }
} as const;

export const ProfileSnapshotExpandedCollectionSchema = {
    properties: {
        snapshots: {
            items: {
                '$ref': '#/components/schemas/ProfileSnapshotExpanded'
            },
            type: 'array',
            title: 'Snapshots'
        },
        missing_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Missing Usernames'
        },
        expired_usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Expired Usernames'
        }
    },
    type: 'object',
    required: ['snapshots'],
    title: 'ProfileSnapshotExpandedCollection',
    description: 'A container holding a list of `ProfileSnapshotExpanded` instances.'
} as const;

export const ProfileUsernamesSchema = {
    properties: {
        usernames: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Usernames'
        }
    },
    type: 'object',
    required: ['usernames'],
    title: 'ProfileUsernames'
} as const;

export const ReelItemSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        play_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Play Count'
        },
        comment_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment Count'
        },
        like_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Like Count'
        },
        media_type: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Type'
        },
        product_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'ReelItem',
    description: 'Single reel payload stored inside a ReelsDocument.'
} as const;

export const ReelMetricsSchema = {
    properties: {
        total_reels: {
            type: 'integer',
            title: 'Total Reels'
        },
        total_plays: {
            type: 'integer',
            title: 'Total Plays'
        },
        avg_plays: {
            type: 'number',
            title: 'Avg Plays'
        },
        avg_reel_likes: {
            type: 'number',
            title: 'Avg Reel Likes'
        },
        avg_reel_comments: {
            type: 'number',
            title: 'Avg Reel Comments'
        }
    },
    type: 'object',
    required: ['total_reels', 'total_plays', 'avg_plays', 'avg_reel_likes', 'avg_reel_comments'],
    title: 'ReelMetrics'
} as const;

export const ReelsDocumentSchema = {
    properties: {
        _id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        profile_id: {
            type: 'string',
            title: 'Profile Id'
        },
        reels: {
            items: {
                '$ref': '#/components/schemas/ReelItem'
            },
            type: 'array',
            title: 'Reels'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['profile_id', 'updated_at'],
    title: 'ReelsDocument',
    description: 'Container for the latest list of reels for a profile.',
    example: {
        id: '65c2f0b7f6b7a8c1c3d4e5f7',
        profile_id: '65c2f0b7f6b7a8c1c3d4e5aa',
        reels: [
            {
                code: 'Coc1nRTAL7v',
                comment_count: 47,
                like_count: 6649,
                media_type: 2,
                play_count: 647430,
                product_type: 'clips'
            }
        ],
        updated_at: '2024-02-12T15:04:05Z'
    }
} as const;

export const ReelsDocumentCollectionSchema = {
    properties: {
        reels: {
            items: {
                '$ref': '#/components/schemas/ReelsDocument'
            },
            type: 'array',
            title: 'Reels'
        }
    },
    type: 'object',
    required: ['reels'],
    title: 'ReelsDocumentCollection',
    description: 'A container holding a list of `ReelsDocument` instances.'
} as const;

export const ReputationCampaignStrategyRequestSchema = {
    properties: {
        brand_name: {
            type: 'string',
            maxLength: 120,
            minLength: 1,
            title: 'Brand Name',
            description: 'Nombre de la marca.'
        },
        brand_context: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Brand Context',
            description: 'Contexto general de la marca (max 250 caracteres).'
        },
        brand_urls: {
            items: {
                type: 'string',
                maxLength: 2083,
                minLength: 1,
                format: 'uri'
            },
            type: 'array',
            maxItems: 3,
            title: 'Brand Urls',
            description: 'Lista de URLs de marca (max 3).'
        },
        brand_goals_type: {
            type: 'string',
            title: 'Brand Goals Type',
            description: 'Goal principal de marca.'
        },
        brand_goals_context: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Brand Goals Context',
            description: 'Contexto adicional del goal de marca (max 250 caracteres).'
        },
        audience: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 5,
            minItems: 1,
            title: 'Audience',
            description: 'Audiencias objetivo de la campana.'
        },
        timeframe: {
            type: 'string',
            title: 'Timeframe',
            description: 'Horizonte temporal de la campana.'
        },
        profiles_list: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 15,
            title: 'Profiles List',
            description: 'Lista de creator usernames (max 15). Puede estar vacia solo cuando brand_goals_type es Crisis.'
        },
        campaign_type: {
            type: 'string',
            title: 'Campaign Type',
            description: 'Estrategia de campana seleccionada.',
            examples: ['all_micro_performance_community_trust']
        },
        generate_html: {
            type: 'boolean',
            title: 'Generate Html',
            description: 'Indica si debe generarse el HTML.',
            default: true
        },
        generate_pdf: {
            type: 'boolean',
            title: 'Generate Pdf',
            description: 'Indica si debe generarse el PDF.',
            default: false
        }
    },
    type: 'object',
    required: ['brand_name', 'brand_context', 'brand_goals_type', 'brand_goals_context', 'audience', 'timeframe', 'profiles_list', 'campaign_type'],
    title: 'ReputationCampaignStrategyRequest',
    example: {
        audience: ['Gen Z', 'Millennials'],
        brand_context: 'Marca de skincare con enfoque en ingredientes limpios.',
        brand_goals_context: 'Incrementar la confianza de compra en Q2.',
        brand_goals_type: 'Trust & Credibility Acceleration',
        brand_name: 'Acme',
        brand_urls: ['https://acme.com', 'https://instagram.com/acme'],
        campaign_type: 'all_micro_performance_community_trust',
        generate_html: true,
        generate_pdf: false,
        profiles_list: ['creator_one', 'creator_two'],
        timeframe: '6 months'
    }
} as const;

export const ReputationCreatorStrategyRequestSchema = {
    properties: {
        creator_username: {
            type: 'string',
            maxLength: 30,
            minLength: 1,
            title: 'Creator Username',
            description: 'Username del creador.'
        },
        creator_context: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Creator Context',
            description: 'Contexto general del creador.'
        },
        creator_urls: {
            items: {
                type: 'string',
                maxLength: 2083,
                minLength: 1,
                format: 'uri'
            },
            type: 'array',
            maxItems: 3,
            title: 'Creator Urls',
            description: 'Lista de URLs del creador (max 3).'
        },
        goal_type: {
            type: 'string',
            title: 'Goal Type',
            description: 'Goal principal de reputacion para creator strategy.'
        },
        goal_context: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Goal Context',
            description: 'Contexto adicional del goal de reputacion.'
        },
        audience: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 5,
            minItems: 1,
            title: 'Audience',
            description: 'Audiencias objetivo.'
        },
        timeframe: {
            type: 'string',
            title: 'Timeframe',
            description: 'Horizonte temporal de la estrategia.'
        },
        primary_platforms: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 6,
            minItems: 1,
            title: 'Primary Platforms',
            description: 'Plataformas principales del creador.'
        },
        reputation_signals: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ReputationSignalsInput'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Senales de reputacion con opciones: strengths, weaknesses, incidents, concerns.'
        },
        collaborators_list: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array',
                    maxItems: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Collaborators List',
            description: 'Lista de colaboradores relevantes (max 10).'
        },
        generate_html: {
            type: 'boolean',
            title: 'Generate Html',
            description: 'Indica si debe generarse el HTML.',
            default: true
        },
        generate_pdf: {
            type: 'boolean',
            title: 'Generate Pdf',
            description: 'Indica si debe generarse el PDF.',
            default: false
        }
    },
    type: 'object',
    required: ['creator_username', 'creator_context', 'goal_type', 'goal_context', 'audience', 'timeframe', 'primary_platforms'],
    title: 'ReputationCreatorStrategyRequest',
    example: {
        audience: ['Gen Z', 'Millennials'],
        collaborators_list: ['brand_one', 'brand_two'],
        creator_context: 'Creador de bienestar y productividad con comunidad activa.',
        creator_urls: ['https://instagram.com/creator_one', 'https://youtube.com/@creator_one'],
        creator_username: 'creator_one',
        generate_html: true,
        generate_pdf: false,
        goal_context: 'Fortalecer percepcion de credibilidad en lanzamientos patrocinados.',
        goal_type: 'Community Trust',
        primary_platforms: ['Instagram', 'YouTube'],
        reputation_signals: {
            concerns: ['fatiga por exceso de colaboraciones'],
            strengths: ['transparencia', 'consistencia de contenido']
        },
        timeframe: '6 months'
    }
} as const;

export const ReputationSignalsInputSchema = {
    properties: {
        strengths: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Strengths'
        },
        weaknesses: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Weaknesses'
        },
        incidents: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Incidents'
        },
        concerns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Concerns'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'ReputationSignalsInput'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdateIgCredentialSchema = {
    properties: {
        login_username: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Login Username'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        session: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Session'
        }
    },
    type: 'object',
    title: 'UpdateIgCredential',
    description: 'Optional updates to be made to an Instagram credential document.',
    example: {
        password: 'new_plain_password',
        session: {
            cookies: []
        }
    }
} as const;

export const UpdateMetricsSchema = {
    properties: {
        post_metrics: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PostMetrics'
                },
                {
                    type: 'null'
                }
            ]
        },
        reel_metrics: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ReelMetrics'
                },
                {
                    type: 'null'
                }
            ]
        },
        overall_post_engagement_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Overall Post Engagement Rate'
        },
        reel_engagement_rate_on_plays: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reel Engagement Rate On Plays'
        }
    },
    type: 'object',
    title: 'UpdateMetrics',
    description: 'A set of optional updates to metrics.',
    example: {
        overall_post_engagement_rate: 0.5734,
        reel_engagement_rate_on_plays: 0.1435
    }
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 25,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UpdatePostsDocumentSchema = {
    properties: {
        posts: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/PostItem'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Posts'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    title: 'UpdatePostsDocument',
    description: 'A set of optional updates to a PostsDocument record.',
    example: {
        posts: [
            {
                caption_text: 'What makes you smile?',
                coauthor_producers: [],
                code: 'CVTH2dLvmkt',
                comment_count: 860,
                is_paid_partnership: false,
                like_count: 141588,
                media_type: 8,
                product_type: 'carousel_container',
                usertags: ['nickthiessen']
            }
        ],
        updated_at: '2024-02-12T15:04:05Z'
    }
} as const;

export const UpdateProfileSchema = {
    properties: {
        ig_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ig Id'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        biography: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Biography'
        },
        is_private: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Private'
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified'
        },
        profile_pic_url: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1,
                    format: 'uri'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Pic Url'
        },
        external_url: {
            anyOf: [
                {
                    type: 'string',
                    minLength: 1,
                    format: 'uri'
                },
                {
                    type: 'null'
                }
            ],
            title: 'External Url'
        },
        updated_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated Date'
        },
        follower_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Follower Count'
        },
        following_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Following Count'
        },
        media_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Media Count'
        },
        bio_links: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/BioLink'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio Links'
        },
        ai_categories: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Categories'
        },
        ai_roles: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Roles'
        }
    },
    type: 'object',
    title: 'UpdateProfile',
    description: `A set of optional updates to be made to a Profile document in the database.
(All fields optional; \`id\` cannot be modified.)`,
    example: {
        ai_categories: ['Motherhood / Family / Parenting', 'Gaming / Esports / Streaming'],
        ai_roles: ['Aspirational / Lifestyle', 'Entertainment'],
        bio_links: [
            {
                title: 'Twitch',
                url: 'http://twitch.tv/stpeach'
            },
            {
                title: 'YouTube',
                url: 'http://youtube.com/stpeach'
            }
        ],
        biography: 'Fitness & lifestyle creator. Links below 👇',
        external_url: 'https://twitch.tv/stpeach',
        is_private: false
    }
} as const;

export const UpdateProfileSnapshotSchema = {
    properties: {
        profile_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        post_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Post Ids'
        },
        reel_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reel Ids'
        },
        metrics_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metrics Id'
        },
        scraped_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scraped At'
        }
    },
    type: 'object',
    title: 'UpdateProfileSnapshot',
    description: 'A set of optional updates to a ProfileSnapshot document.',
    example: {
        metrics_id: '65c2f0b7f6b7a8c1c3d4e8c1'
    }
} as const;

export const UpdateReelsDocumentSchema = {
    properties: {
        reels: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ReelItem'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reels'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    title: 'UpdateReelsDocument',
    description: 'A set of optional updates to a ReelsDocument record.',
    example: {
        reels: [
            {
                code: 'Coc1nRTAL7v',
                comment_count: 47,
                like_count: 6649,
                media_type: 2,
                play_count: 647430,
                product_type: 'clips'
            }
        ],
        updated_at: '2024-02-12T15:04:05Z'
    }
} as const;

export const UserAdminPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['id', 'email', 'role', 'is_active'],
    title: 'UserAdminPublic'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 25,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 25,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WaitingListCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        interest: {
            type: 'string',
            enum: ['public_relations', 'marketing', 'creator', 'creator_talent_management', 'publicity', 'other'],
            title: 'Interest'
        }
    },
    type: 'object',
    required: ['email', 'interest'],
    title: 'WaitingListCreate'
} as const;