// This file is auto-generated by @hey-api/openapi-ts

export type BioLink = {
    title: string;
    url: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Container for a single Instagram credential record.
 */
export type IgCredential = {
    _id?: (string | null);
    login_username: string;
    password: string;
    session?: ({
    [key: string]: unknown;
} | null);
};

/**
 * Public view of a single Instagram credential record.
 */
export type IgCredentialPublic = {
    _id?: (string | null);
    login_username: string;
    session?: ({
    [key: string]: unknown;
} | null);
};

/**
 * A container holding a list of `IgCredentialPublic` instances.
 */
export type IgCredentialPublicCollection = {
    ig_credentials: Array<IgCredentialPublic>;
};

/**
 * Payload for testing the Instagram OpenAI classifier.
 */
export type InstagramAIRequest = {
    profiles: Array<InstagramProfileInput>;
};

export type InstagramAIResponse = {
    results: Array<InstagramAIResult>;
};

export type InstagramAIResult = {
    username: string;
    categories: Array<(string)>;
    roles: Array<(string)>;
};

export type InstagramBatchCountersSchema = {
    requested?: number;
    successful?: number;
    failed?: number;
    not_found?: number;
};

export type InstagramBatchRecommendationsResponse = {
    usernames?: Array<InstagramBatchUsernameStatus>;
    recommendations?: {
        [key: string]: Array<InstagramSuggestedUserSchema>;
    };
    counters?: InstagramBatchCountersSchema;
    error?: (string | null);
};

export type InstagramBatchScrapeRequest = {
    usernames: Array<(string)>;
    timeout_ms?: number;
    headless?: boolean;
    user_agent?: string;
    locale?: string;
    max_posts?: number;
    max_concurrent?: number;
    /**
     * Maximum recommended users returned per profile.
     */
    recommended_limit?: number;
    proxy?: (string | null);
};

export type InstagramBatchScrapeSummaryResponse = {
    usernames?: Array<InstagramBatchUsernameStatus>;
    counters?: InstagramBatchCountersSchema;
    error?: (string | null);
};

export type InstagramBatchUsernameStatus = {
    username: string;
    status: 'success' | 'failed' | 'skipped' | 'not_found';
    error?: (string | null);
};

export type status = 'success' | 'failed' | 'skipped' | 'not_found';

export type InstagramPostSchema = {
    code?: (string | null);
    caption_text?: (string | null);
    is_paid_partnership?: (boolean | null);
    sponsor_tags?: unknown;
    coauthor_producers?: Array<(string)>;
    comment_count?: (number | null);
    like_count?: (number | null);
    usertags?: Array<(string)>;
    timestamp?: (number | null);
    media_type?: (number | null);
    product_type?: (string | null);
};

export type InstagramProfileInput = {
    username: string;
    biography?: (string | null);
    follower_count?: (number | null);
    posts?: Array<InstagramPostSchema>;
};

/**
 * Payload para generar reportes de Instagram.
 */
export type InstagramReportRequest = {
    /**
     * Lista de usernames a usar para generar los reportes (max 20).
     */
    usernames: Array<(string)>;
    /**
     * Nombre de la plantilla a renderizar.
     */
    template_name?: string;
    /**
     * Indica si debe generarse el HTML como parte del proceso.
     */
    generate_html?: boolean;
    /**
     * Indica si debe generarse un PDF a partir del HTML.
     */
    generate_pdf?: boolean;
};

export type InstagramScrapeJobCreateRequest = {
    usernames: Array<(string)>;
    timeout_ms?: number;
    headless?: boolean;
    user_agent?: string;
    locale?: string;
    max_posts?: number;
    max_concurrent?: number;
    /**
     * Maximum recommended users returned per profile.
     */
    recommended_limit?: number;
    proxy?: (string | null);
};

export type InstagramScrapeJobCreateResponse = {
    job_id: string;
    status: "queued";
};

export type InstagramScrapeJobReferences = {
    all_usernames?: Array<(string)>;
    successful_usernames?: Array<(string)>;
    failed_usernames?: Array<(string)>;
    skipped_usernames?: Array<(string)>;
    not_found_usernames?: Array<(string)>;
};

export type InstagramScrapeJobStatusResponse = {
    job_id: string;
    status: 'queued' | 'running' | 'done' | 'failed';
    created_at: string;
    updated_at: string;
    expires_at: string;
    attempts?: number;
    lease_owner?: (string | null);
    leased_until?: (string | null);
    heartbeat_at?: (string | null);
    summary?: (InstagramBatchScrapeSummaryResponse | null);
    references?: (InstagramScrapeJobReferences | null);
    error?: (string | null);
};

export type status2 = 'queued' | 'running' | 'done' | 'failed';

export type InstagramSuggestedUserSchema = {
    username?: (string | null);
    id?: (string | null);
    full_name?: (string | null);
    profile_pic_url?: (string | null);
};

export type Message = {
    message: string;
};

/**
 * Container for metrics derived from posts and reels.
 */
export type Metrics = {
    _id?: (string | null);
    post_metrics: PostMetrics;
    reel_metrics: ReelMetrics;
    overall_engagement_rate: number;
};

/**
 * A container holding a list of `Metrics` instances.
 */
export type MetricsCollection = {
    metrics: Array<Metrics>;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Single post payload stored inside a PostsDocument.
 */
export type PostItem = {
    code: string;
    caption_text?: (string | null);
    is_paid_partnership?: (boolean | null);
    coauthor_producers?: Array<(string)>;
    comment_count?: (number | null);
    like_count?: (number | null);
    usertags?: Array<(string)>;
    media_type?: (number | null);
    product_type?: (string | null);
};

export type PostMetrics = {
    total_posts: number;
    total_likes: number;
    total_comments: number;
    avg_likes: number;
    avg_comments: number;
    avg_engagement_rate: number;
    hashtags_per_post: number;
    mentions_per_post: number;
};

/**
 * Container for the latest list of posts for a profile.
 */
export type PostsDocument = {
    _id?: (string | null);
    profile_id: string;
    posts?: Array<PostItem>;
    updated_at: string;
};

/**
 * A container holding a list of `PostsDocument` instances.
 */
export type PostsDocumentCollection = {
    posts: Array<PostsDocument>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Container for a single profile record.
 */
export type Profile = {
    _id?: (string | null);
    ig_id: string;
    username: string;
    full_name: string;
    biography: string;
    is_private: boolean;
    is_verified: boolean;
    profile_pic_url: string;
    external_url?: (string | null);
    updated_date: string;
    follower_count: number;
    following_count: number;
    media_count: number;
    bio_links?: (Array<BioLink> | null);
    ai_categories?: (Array<(string)> | null);
    ai_roles?: (Array<(string)> | null);
};

/**
 * A container holding a list of `Profile` instances
 */
export type ProfileCollection = {
    profiles: Array<Profile>;
};

/**
 * Relates a profile to scraped posts, reels, and metrics at a point in time.
 */
export type ProfileSnapshot = {
    _id?: (string | null);
    profile_id: string;
    post_ids?: Array<(string)>;
    reel_ids?: Array<(string)>;
    metrics_id?: (string | null);
    scraped_at: string;
};

/**
 * A container holding a list of `ProfileSnapshot` instances.
 */
export type ProfileSnapshotCollection = {
    snapshots: Array<ProfileSnapshot>;
};

/**
 * Profile snapshot with full related data resolved via lookup.
 */
export type ProfileSnapshotExpanded = {
    _id?: (string | null);
    profile_id: string;
    post_ids?: Array<(string)>;
    reel_ids?: Array<(string)>;
    metrics_id?: (string | null);
    scraped_at: string;
    profile?: (Profile | null);
    posts?: Array<PostsDocument>;
    reels?: Array<ReelsDocument>;
    metrics?: (Metrics | null);
};

/**
 * A container holding a list of `ProfileSnapshotExpanded` instances.
 */
export type ProfileSnapshotExpandedCollection = {
    snapshots: Array<ProfileSnapshotExpanded>;
};

export type ProfileUsernames = {
    usernames: Array<(string)>;
};

/**
 * Single reel payload stored inside a ReelsDocument.
 */
export type ReelItem = {
    code: string;
    play_count?: (number | null);
    comment_count?: (number | null);
    like_count?: (number | null);
    media_type?: (number | null);
    product_type?: (string | null);
};

export type ReelMetrics = {
    total_reels: number;
    total_plays: number;
    avg_plays: number;
    avg_reel_likes: number;
    avg_reel_comments: number;
};

/**
 * Container for the latest list of reels for a profile.
 */
export type ReelsDocument = {
    _id?: (string | null);
    profile_id: string;
    reels?: Array<ReelItem>;
    updated_at: string;
};

/**
 * A container holding a list of `ReelsDocument` instances.
 */
export type ReelsDocumentCollection = {
    reels: Array<ReelsDocument>;
};

export type ReputationCampaignStrategyRequest = {
    /**
     * Nombre de la marca.
     */
    brand_name: string;
    /**
     * Contexto general de la marca (max 250 caracteres).
     */
    brand_context: string;
    /**
     * Lista de URLs de marca (max 3).
     */
    brand_urls?: Array<(string)>;
    /**
     * Goal principal de marca.
     */
    brand_goals_type: string;
    /**
     * Contexto adicional del goal de marca (max 250 caracteres).
     */
    brand_goals_context: string;
    /**
     * Audiencias objetivo de la campana.
     */
    audience: Array<(string)>;
    /**
     * Horizonte temporal de la campana.
     */
    timeframe: string;
    /**
     * Lista de perfiles (max 15).
     */
    profiles_list: Array<(string)>;
    /**
     * Estrategia de campana seleccionada.
     */
    campaign_type: string;
    /**
     * Indica si debe generarse el HTML.
     */
    generate_html?: boolean;
    /**
     * Indica si debe generarse el PDF.
     */
    generate_pdf?: boolean;
};

export type ReputationCreatorStrategyRequest = {
    /**
     * Username del creador.
     */
    creator_username: string;
    /**
     * Contexto general del creador.
     */
    creator_context: string;
    /**
     * Lista de URLs del creador (max 3).
     */
    creator_urls?: Array<(string)>;
    /**
     * Goal principal de reputacion para creator strategy.
     */
    goal_type: string;
    /**
     * Contexto adicional del goal de reputacion.
     */
    goal_context: string;
    /**
     * Audiencias objetivo.
     */
    audience: Array<(string)>;
    /**
     * Horizonte temporal de la estrategia.
     */
    timeframe: string;
    /**
     * Plataformas principales del creador.
     */
    primary_platforms: Array<(string)>;
    /**
     * Senales de reputacion con opciones: strengths, weaknesses, incidents, concerns.
     */
    reputation_signals?: (ReputationSignalsInput | null);
    /**
     * Lista de colaboradores relevantes (max 10).
     */
    collaborators_list?: (Array<(string)> | null);
    /**
     * Indica si debe generarse el HTML.
     */
    generate_html?: boolean;
    /**
     * Indica si debe generarse el PDF.
     */
    generate_pdf?: boolean;
};

export type ReputationSignalsInput = {
    strengths?: Array<(string)>;
    weaknesses?: Array<(string)>;
    incidents?: Array<(string)>;
    concerns?: Array<(string)>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Optional updates to be made to an Instagram credential document.
 */
export type UpdateIgCredential = {
    login_username?: (string | null);
    password?: (string | null);
    session?: ({
    [key: string]: unknown;
} | null);
};

/**
 * A set of optional updates to metrics.
 */
export type UpdateMetrics = {
    post_metrics?: (PostMetrics | null);
    reel_metrics?: (ReelMetrics | null);
    overall_engagement_rate?: (number | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * A set of optional updates to a PostsDocument record.
 */
export type UpdatePostsDocument = {
    posts?: (Array<PostItem> | null);
    updated_at?: (string | null);
};

/**
 * A set of optional updates to be made to a Profile document in the database.
 * (All fields optional; `id` cannot be modified.)
 */
export type UpdateProfile = {
    ig_id?: (string | null);
    username?: (string | null);
    full_name?: (string | null);
    biography?: (string | null);
    is_private?: (boolean | null);
    is_verified?: (boolean | null);
    profile_pic_url?: (string | null);
    external_url?: (string | null);
    updated_date?: (string | null);
    follower_count?: (number | null);
    following_count?: (number | null);
    media_count?: (number | null);
    bio_links?: (Array<BioLink> | null);
    ai_categories?: (Array<(string)> | null);
    ai_roles?: (Array<(string)> | null);
};

/**
 * A set of optional updates to a ProfileSnapshot document.
 */
export type UpdateProfileSnapshot = {
    profile_id?: (string | null);
    post_ids?: (Array<(string)> | null);
    reel_ids?: (Array<(string)> | null);
    metrics_id?: (string | null);
    scraped_at?: (string | null);
};

/**
 * A set of optional updates to a ReelsDocument record.
 */
export type UpdateReelsDocument = {
    reels?: (Array<ReelItem> | null);
    updated_at?: (string | null);
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type BrandIntelligenceGenerateReputationCampaignStrategyEndpointData = {
    requestBody: ReputationCampaignStrategyRequest;
};

export type BrandIntelligenceGenerateReputationCampaignStrategyEndpointResponse = (unknown);

export type BrandIntelligenceGenerateReputationCreatorStrategyEndpointData = {
    requestBody: ReputationCreatorStrategyRequest;
};

export type BrandIntelligenceGenerateReputationCreatorStrategyEndpointResponse = (unknown);

export type IgCredentialsCreateIgCredentialEndpointData = {
    requestBody: IgCredential;
};

export type IgCredentialsCreateIgCredentialEndpointResponse = (IgCredentialPublic);

export type IgCredentialsReadIgCredentialsData = {
    limit?: number;
    skip?: number;
};

export type IgCredentialsReadIgCredentialsResponse = (IgCredentialPublicCollection);

export type IgCredentialsReadIgCredentialData = {
    credentialId: string;
};

export type IgCredentialsReadIgCredentialResponse = (IgCredentialPublic);

export type IgCredentialsUpdateIgCredentialEndpointData = {
    credentialId: string;
    requestBody: UpdateIgCredential;
};

export type IgCredentialsUpdateIgCredentialEndpointResponse = (IgCredentialPublic);

export type IgCredentialsReplaceIgCredentialEndpointData = {
    credentialId: string;
    requestBody: IgCredential;
};

export type IgCredentialsReplaceIgCredentialEndpointResponse = (IgCredentialPublic);

export type IgCredentialsDeleteIgCredentialEndpointData = {
    credentialId: string;
};

export type IgCredentialsDeleteIgCredentialEndpointResponse = (IgCredentialPublic);

export type IgMetricsCreateIgMetricsData = {
    requestBody: Metrics;
};

export type IgMetricsCreateIgMetricsResponse = (Metrics);

export type IgMetricsReadIgMetricsData = {
    limit?: number;
    skip?: number;
};

export type IgMetricsReadIgMetricsResponse = (MetricsCollection);

export type IgMetricsReadIgMetricsByIdData = {
    metricsId: string;
};

export type IgMetricsReadIgMetricsByIdResponse = (Metrics);

export type IgMetricsUpdateIgMetricsData = {
    metricsId: string;
    requestBody: UpdateMetrics;
};

export type IgMetricsUpdateIgMetricsResponse = (Metrics);

export type IgMetricsReplaceIgMetricsData = {
    metricsId: string;
    requestBody: Metrics;
};

export type IgMetricsReplaceIgMetricsResponse = (Metrics);

export type IgMetricsDeleteIgMetricsData = {
    metricsId: string;
};

export type IgMetricsDeleteIgMetricsResponse = (Metrics);

export type IgPostsCreateIgPostData = {
    requestBody: PostsDocument;
};

export type IgPostsCreateIgPostResponse = (PostsDocument);

export type IgPostsReadIgPostsData = {
    limit?: number;
    skip?: number;
};

export type IgPostsReadIgPostsResponse = (PostsDocumentCollection);

export type IgPostsReadIgPostData = {
    postId: string;
};

export type IgPostsReadIgPostResponse = (PostsDocument);

export type IgPostsUpdateIgPostData = {
    postId: string;
    requestBody: UpdatePostsDocument;
};

export type IgPostsUpdateIgPostResponse = (PostsDocument);

export type IgPostsReplaceIgPostData = {
    postId: string;
    requestBody: PostsDocument;
};

export type IgPostsReplaceIgPostResponse = (PostsDocument);

export type IgPostsDeleteIgPostData = {
    postId: string;
};

export type IgPostsDeleteIgPostResponse = (PostsDocument);

export type IgProfilesCreateIgProfileData = {
    requestBody: Profile;
};

export type IgProfilesCreateIgProfileResponse = (Profile);

export type IgProfilesReadIgProfilesData = {
    limit?: number;
    skip?: number;
};

export type IgProfilesReadIgProfilesResponse = (ProfileCollection);

export type IgProfilesReadIgProfileByUsernameData = {
    username: string;
};

export type IgProfilesReadIgProfileByUsernameResponse = (Profile);

export type IgProfilesReadIgProfilesByUsernamesData = {
    requestBody: ProfileUsernames;
};

export type IgProfilesReadIgProfilesByUsernamesResponse = (ProfileCollection);

export type IgProfilesReadIgProfileData = {
    profileId: string;
};

export type IgProfilesReadIgProfileResponse = (Profile);

export type IgProfilesUpdateIgProfileData = {
    profileId: string;
    requestBody: UpdateProfile;
};

export type IgProfilesUpdateIgProfileResponse = (Profile);

export type IgProfilesReplaceIgProfileData = {
    profileId: string;
    requestBody: Profile;
};

export type IgProfilesReplaceIgProfileResponse = (Profile);

export type IgProfilesDeleteIgProfileData = {
    profileId: string;
};

export type IgProfilesDeleteIgProfileResponse = (Profile);

export type IgProfileSnapshotsCreateIgProfileSnapshotData = {
    requestBody: ProfileSnapshot;
};

export type IgProfileSnapshotsCreateIgProfileSnapshotResponse = (ProfileSnapshot);

export type IgProfileSnapshotsReadIgProfileSnapshotsData = {
    limit?: number;
    skip?: number;
    snapshotIds?: (Array<(string)> | null);
};

export type IgProfileSnapshotsReadIgProfileSnapshotsResponse = (ProfileSnapshotCollection);

export type IgProfileSnapshotsReadIgProfileSnapshotsAdvancedData = {
    limit?: number;
    skip?: number;
    usernames?: (Array<(string)> | null);
};

export type IgProfileSnapshotsReadIgProfileSnapshotsAdvancedResponse = (ProfileSnapshotExpandedCollection);

export type IgProfileSnapshotsReadIgProfileSnapshotData = {
    snapshotId: string;
};

export type IgProfileSnapshotsReadIgProfileSnapshotResponse = (ProfileSnapshot);

export type IgProfileSnapshotsUpdateIgProfileSnapshotData = {
    requestBody: UpdateProfileSnapshot;
    snapshotId: string;
};

export type IgProfileSnapshotsUpdateIgProfileSnapshotResponse = (ProfileSnapshot);

export type IgProfileSnapshotsReplaceIgProfileSnapshotData = {
    requestBody: ProfileSnapshot;
    snapshotId: string;
};

export type IgProfileSnapshotsReplaceIgProfileSnapshotResponse = (ProfileSnapshot);

export type IgProfileSnapshotsDeleteIgProfileSnapshotData = {
    snapshotId: string;
};

export type IgProfileSnapshotsDeleteIgProfileSnapshotResponse = (ProfileSnapshot);

export type IgReelsCreateIgReelData = {
    requestBody: ReelsDocument;
};

export type IgReelsCreateIgReelResponse = (ReelsDocument);

export type IgReelsReadIgReelsData = {
    limit?: number;
    skip?: number;
};

export type IgReelsReadIgReelsResponse = (ReelsDocumentCollection);

export type IgReelsReadIgReelData = {
    reelId: string;
};

export type IgReelsReadIgReelResponse = (ReelsDocument);

export type IgReelsUpdateIgReelData = {
    reelId: string;
    requestBody: UpdateReelsDocument;
};

export type IgReelsUpdateIgReelResponse = (ReelsDocument);

export type IgReelsReplaceIgReelData = {
    reelId: string;
    requestBody: ReelsDocument;
};

export type IgReelsReplaceIgReelResponse = (ReelsDocument);

export type IgReelsDeleteIgReelData = {
    reelId: string;
};

export type IgReelsDeleteIgReelResponse = (ReelsDocument);

export type InstagramCreateInstagramScrapeJobData = {
    requestBody: InstagramScrapeJobCreateRequest;
};

export type InstagramCreateInstagramScrapeJobResponse = (InstagramScrapeJobCreateResponse);

export type InstagramGetInstagramScrapeJobData = {
    jobId: string;
};

export type InstagramGetInstagramScrapeJobResponse = (InstagramScrapeJobStatusResponse);

export type InstagramInstagramScrapeProfilesBatchData = {
    requestBody: InstagramBatchScrapeRequest;
};

export type InstagramInstagramScrapeProfilesBatchResponse = (InstagramBatchScrapeSummaryResponse);

export type InstagramInstagramProfilesRecommendationsData = {
    requestBody: InstagramBatchScrapeRequest;
};

export type InstagramInstagramProfilesRecommendationsResponse = (InstagramBatchRecommendationsResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OpenaiRunInstagramAiData = {
    requestBody: InstagramAIRequest;
};

export type OpenaiRunInstagramAiResponse = (InstagramAIResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SocialMediaReportGenerateInstagramReportEndpointData = {
    requestBody: InstagramReportRequest;
};

export type SocialMediaReportGenerateInstagramReportEndpointResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);