import {
  Box,
  Link as ChakraLink,
  Heading,
  Stack,
  Table,
  Text,
} from "@chakra-ui/react"
import { Link as RouterLink } from "@tanstack/react-router"
import { useEffect } from "react"
import InfoPageShell from "@/components/Common/InfoPageShell"

export function CookieTablesPage() {
  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: "auto" })
  }, [])

  return (
    <InfoPageShell maxW="7xl" useSymbolHomeButton>
      <Box layerStyle="infoCard" p={{ base: 6, md: 10 }}>
        <Stack gap={8}>
          <Stack gap={2}>
            <Text textStyle="eyebrow">Company</Text>
            <Heading size={{ base: "2xl", md: "3xl" }} textStyle="pageTitle">
              Kiizama Cookie Tables
            </Heading>
          </Stack>

          <Stack as="section" gap={4}>
            <Text textStyle="pageBody">
              These Cookie Tables provide additional information about Cookies
              that Kiizama uses on our Website and Services. Only Strictly
              Necessary Cookies are used in our mobile apps.
            </Text>
            <Text textStyle="pageBody">
              Please refer to our{" "}
              <RouterLink to="/cookie-notice" className="legal-link">
                Cookie Notice
              </RouterLink>{" "}
              for additional information, including instructions for how to
              disable Cookies. If you have any questions about our use of
              Cookies, you can email us at{" "}
              <ChakraLink
                href="mailto:admin@kiizama.com"
                className="legal-link"
              >
                admin@kiizama.com
              </ChakraLink>
              .
            </Text>
          </Stack>

          <Stack as="section" gap={4}>
            <Heading size="lg">Strictly Necessary Cookies</Heading>
            <Box overflowX="auto">
              <Table.Root size={{ base: "sm", md: "md" }} minW="980px">
                <Table.Header>
                  <Table.Row>
                    <Table.ColumnHeader>Cookie Name</Table.ColumnHeader>
                    <Table.ColumnHeader>Duration</Table.ColumnHeader>
                    <Table.ColumnHeader>Domain</Table.ColumnHeader>
                    <Table.ColumnHeader>Purpose</Table.ColumnHeader>
                    <Table.ColumnHeader>Provider</Table.ColumnHeader>
                  </Table.Row>
                </Table.Header>
                <Table.Body>
                  <Table.Row>
                    <Table.Cell>access_token</Table.Cell>
                    <Table.Cell>session</Table.Cell>
                    <Table.Cell>Local Storage</Table.Cell>
                    <Table.Cell>JWT Authentication</Table.Cell>
                    <Table.Cell>Kiizama</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>theme</Table.Cell>
                    <Table.Cell>
                      Persistent until changed or browser storage is cleared
                    </Table.Cell>
                    <Table.Cell>Local Storage</Table.Cell>
                    <Table.Cell>
                      Used to remember UI/UX settings selected by the user, such
                      as the application appearance mode.
                    </Table.Cell>
                    <Table.Cell>Kiizama</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>kiizama-overview-local-reports</Table.Cell>
                    <Table.Cell>
                      Persistent until deleted by the user or browser storage is
                      cleared
                    </Table.Cell>
                    <Table.Cell>Local Storage</Table.Cell>
                    <Table.Cell>
                      Used to store locally available reports generated by or
                      for the user so the Services can show the reports the user
                      chooses to keep. The user controls which reports to
                      maintain locally and may delete them at any time;
                      downloaded report files remain under the user&apos;s
                      device and browser controls where applicable.
                    </Table.Cell>
                    <Table.Cell>Kiizama</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>kiizama-creators-search-jobs</Table.Cell>
                    <Table.Cell>
                      Persistent until removed by the user, replaced by newer
                      jobs, or browser storage is cleared
                    </Table.Cell>
                    <Table.Cell>Local Storage</Table.Cell>
                    <Table.Cell>
                      Used to remember limited recent search activity and
                      related status information so the Services can maintain a
                      consistent user experience after navigation or reload.
                    </Table.Cell>
                    <Table.Cell>Kiizama</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>user-events:last-event-id</Table.Cell>
                    <Table.Cell>
                      Temporary browser-session storage, cleared automatically
                      or when browser session storage is cleared
                    </Table.Cell>
                    <Table.Cell>Session Storage</Table.Cell>
                    <Table.Cell>
                      Used to support continuity for in-session service updates
                      and reduce duplicate processing during normal use of the
                      Services.
                    </Table.Cell>
                    <Table.Cell>Kiizama</Table.Cell>
                  </Table.Row>
                  <Table.Row>
                    <Table.Cell>notion_cookie_consent</Table.Cell>
                    <Table.Cell>365 days</Table.Cell>
                    <Table.Cell>www.kiizama.com</Table.Cell>
                    <Table.Cell>
                      Used to help remember your cookie consent preferences.
                    </Table.Cell>
                    <Table.Cell>Kiizama</Table.Cell>
                  </Table.Row>
                </Table.Body>
              </Table.Root>
            </Box>
          </Stack>

          <Stack as="section" gap={4}>
            <Heading size="lg">Functional Cookies</Heading>
            <Box overflowX="auto">
              <Table.Root size={{ base: "sm", md: "md" }} minW="980px">
                <Table.Header>
                  <Table.Row>
                    <Table.ColumnHeader>Cookie Name</Table.ColumnHeader>
                    <Table.ColumnHeader>Duration</Table.ColumnHeader>
                    <Table.ColumnHeader>Domain</Table.ColumnHeader>
                    <Table.ColumnHeader>Purpose</Table.ColumnHeader>
                    <Table.ColumnHeader>Provider</Table.ColumnHeader>
                  </Table.Row>
                </Table.Header>
                <Table.Body>
                  <Table.Row>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                  </Table.Row>
                </Table.Body>
              </Table.Root>
            </Box>
          </Stack>

          <Stack as="section" gap={4}>
            <Heading size="lg">Analytics Cookies</Heading>
            <Box overflowX="auto">
              <Table.Root size={{ base: "sm", md: "md" }} minW="980px">
                <Table.Header>
                  <Table.Row>
                    <Table.ColumnHeader>Cookie Name</Table.ColumnHeader>
                    <Table.ColumnHeader>Duration</Table.ColumnHeader>
                    <Table.ColumnHeader>Domain</Table.ColumnHeader>
                    <Table.ColumnHeader>Purpose</Table.ColumnHeader>
                    <Table.ColumnHeader>Provider</Table.ColumnHeader>
                  </Table.Row>
                </Table.Header>
                <Table.Body>
                  <Table.Row>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                  </Table.Row>
                </Table.Body>
              </Table.Root>
            </Box>
          </Stack>

          <Stack as="section" gap={4}>
            <Heading size="lg">Marketing Cookies</Heading>
            <Box overflowX="auto">
              <Table.Root size={{ base: "sm", md: "md" }} minW="980px">
                <Table.Header>
                  <Table.Row>
                    <Table.ColumnHeader>Cookie Name</Table.ColumnHeader>
                    <Table.ColumnHeader>Duration</Table.ColumnHeader>
                    <Table.ColumnHeader>Domain</Table.ColumnHeader>
                    <Table.ColumnHeader>Purpose</Table.ColumnHeader>
                    <Table.ColumnHeader>Provider</Table.ColumnHeader>
                  </Table.Row>
                </Table.Header>
                <Table.Body>
                  <Table.Row>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                    <Table.Cell> </Table.Cell>
                  </Table.Row>
                </Table.Body>
              </Table.Root>
            </Box>
          </Stack>

          <Text color="ui.mutedText" fontSize="sm">
            Last Updated: May 1, 2026
          </Text>
        </Stack>
      </Box>
    </InfoPageShell>
  )
}
