import { execFileSync } from "node:child_process"
import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises"
import path from "node:path"
import dotenv from "dotenv"
import { parseBlogPostModules } from "../src/features/blog/parser.ts"
import {
  DEFAULT_SITE_URL,
  normalizeSiteUrl,
} from "../src/features/blog/types.ts"

const projectRoot = path.resolve(import.meta.dirname, "..")
const repoRoot = path.resolve(projectRoot, "..")
const contentDir = path.join(projectRoot, "content", "blog")
const outputPath = path.join(
  projectRoot,
  "src",
  "features",
  "blog",
  "posts.generated.ts",
)
const biomeBin = path.join(
  projectRoot,
  "node_modules",
  ".bin",
  process.platform === "win32" ? "biome.cmd" : "biome",
)

dotenv.config({ path: path.join(repoRoot, ".env") })

const siteUrl = normalizeSiteUrl(process.env.VITE_SITE_URL || DEFAULT_SITE_URL)

const loadBlogModules = async () => {
  const entries = await readdir(contentDir)
  const modules: Record<string, string> = {}

  for (const entry of entries) {
    if (!entry.endsWith(".md")) {
      continue
    }

    const filePath = path.join(contentDir, entry)
    const fileStats = await stat(filePath)
    if (!fileStats.isFile()) {
      continue
    }

    modules[filePath] = await readFile(filePath, "utf8")
  }

  return modules
}

const renderGeneratedModule = (
  posts: unknown,
) => `// This file is auto-generated by scripts/generate-blog-content.ts.
// Do not edit it manually.

import type { BlogPost } from "./types"

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)}
`

const main = async () => {
  const modules = await loadBlogModules()
  const posts = parseBlogPostModules(modules, { siteUrl })

  await mkdir(path.dirname(outputPath), { recursive: true })
  await writeFile(outputPath, renderGeneratedModule(posts), "utf8")
  execFileSync(biomeBin, ["format", "--write", outputPath], {
    cwd: projectRoot,
    stdio: "ignore",
  })
}

await main()
