"""instagram_postgres_cutover

Revision ID: 7a1ef1fcfc09
Revises: 20260325_0001
Create Date: 2026-03-27 17:30:36.535292

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7a1ef1fcfc09"
down_revision = "20260325_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS private")

    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM pg_available_extensions
            WHERE name = 'pg_cron'
          ) THEN
            CREATE EXTENSION IF NOT EXISTS pg_cron;
          END IF;
        END
        $$;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ig_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("login_username", sa.String(length=255), nullable=False),
        sa.Column("password_encrypted", sa.String(), nullable=False),
        sa.Column("session_encrypted", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_index(
        "ix_private_ig_credentials_login_username",
        "ig_credentials",
        ["login_username"],
        unique=True,
        schema="private",
    )
    op.create_table(
        "ig_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("total_posts", sa.Integer(), nullable=False),
        sa.Column("total_likes", sa.Integer(), nullable=False),
        sa.Column("total_comments", sa.Integer(), nullable=False),
        sa.Column("avg_likes", sa.Float(), nullable=False),
        sa.Column("avg_comments", sa.Float(), nullable=False),
        sa.Column("avg_engagement_rate", sa.Float(), nullable=False),
        sa.Column("hashtags_per_post", sa.Float(), nullable=False),
        sa.Column("mentions_per_post", sa.Float(), nullable=False),
        sa.Column("total_reels", sa.Integer(), nullable=False),
        sa.Column("total_plays", sa.Integer(), nullable=False),
        sa.Column("avg_plays", sa.Float(), nullable=False),
        sa.Column("avg_reel_likes", sa.Float(), nullable=False),
        sa.Column("avg_reel_comments", sa.Float(), nullable=False),
        sa.Column("overall_post_engagement_rate", sa.Float(), nullable=False),
        sa.Column("reel_engagement_rate_on_plays", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_table(
        "ig_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ig_id", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("biography", sa.String(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("profile_pic_url", sa.String(length=2048), nullable=True),
        sa.Column("profile_pic_src", sa.String(), nullable=True),
        sa.Column("external_url", sa.String(length=2048), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=False),
        sa.Column("following_count", sa.Integer(), nullable=False),
        sa.Column("media_count", sa.Integer(), nullable=False),
        sa.Column("bio_links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ai_categories",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("ai_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_index(
        "ix_private_ig_profiles_ig_id",
        "ig_profiles",
        ["ig_id"],
        unique=True,
        schema="private",
    )
    op.create_index(
        "ix_private_ig_profiles_username",
        "ig_profiles",
        ["username"],
        unique=True,
        schema="private",
    )
    op.create_table(
        "ig_posts_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["private.ig_profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_index(
        "idx_ig_posts_documents_profile_updated_at",
        "ig_posts_documents",
        ["profile_id", "updated_at"],
        unique=False,
        schema="private",
    )
    op.create_index(
        "ix_private_ig_posts_documents_profile_id",
        "ig_posts_documents",
        ["profile_id"],
        unique=False,
        schema="private",
    )
    op.create_table(
        "ig_reels_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["private.ig_profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_index(
        "idx_ig_reels_documents_profile_updated_at",
        "ig_reels_documents",
        ["profile_id", "updated_at"],
        unique=False,
        schema="private",
    )
    op.create_index(
        "ix_private_ig_reels_documents_profile_id",
        "ig_reels_documents",
        ["profile_id"],
        unique=False,
        schema="private",
    )
    op.create_table(
        "ig_scrape_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=255), nullable=True),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("notification_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["private.user.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_index(
        "idx_ig_scrape_jobs_expires_at",
        "ig_scrape_jobs",
        ["expires_at"],
        unique=False,
        schema="private",
    )
    op.create_index(
        "idx_ig_scrape_jobs_owner_created_at",
        "ig_scrape_jobs",
        ["owner_user_id", "created_at"],
        unique=False,
        schema="private",
    )
    op.create_index(
        "idx_ig_scrape_jobs_status_created_at",
        "ig_scrape_jobs",
        ["status", "created_at"],
        unique=False,
        schema="private",
    )
    op.create_index(
        "ix_private_ig_scrape_jobs_owner_user_id",
        "ig_scrape_jobs",
        ["owner_user_id"],
        unique=False,
        schema="private",
    )
    op.create_index(
        "ix_private_ig_scrape_jobs_status",
        "ig_scrape_jobs",
        ["status"],
        unique=False,
        schema="private",
    )
    op.create_table(
        "ig_profile_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("posts_document_id", sa.Uuid(), nullable=True),
        sa.Column("reels_document_id", sa.Uuid(), nullable=True),
        sa.Column("metrics_id", sa.Uuid(), nullable=True),
        sa.Column("scraped_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["metrics_id"], ["private.ig_metrics.id"]),
        sa.ForeignKeyConstraint(
            ["posts_document_id"], ["private.ig_posts_documents.id"]
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["private.ig_profiles.id"]),
        sa.ForeignKeyConstraint(
            ["reels_document_id"], ["private.ig_reels_documents.id"]
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_index(
        "idx_ig_profile_snapshots_profile_scraped_at",
        "ig_profile_snapshots",
        ["profile_id", "scraped_at"],
        unique=False,
        schema="private",
    )
    op.create_index(
        "ix_private_ig_profile_snapshots_profile_id",
        "ig_profile_snapshots",
        ["profile_id"],
        unique=False,
        schema="private",
    )
    # ### end Alembic commands ###

    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM pg_extension
            WHERE extname = 'pg_cron'
          ) THEN
            IF NOT EXISTS (
              SELECT 1
              FROM cron.job
              WHERE jobname = 'cleanup-ig-scrape-jobs'
            ) THEN
              PERFORM cron.schedule(
                'cleanup-ig-scrape-jobs',
                '0 * * * *',
                $job$
                DELETE FROM private.ig_scrape_jobs
                WHERE expires_at < now();
                $job$
              );
            END IF;
          END IF;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF EXISTS (
            SELECT 1
            FROM pg_extension
            WHERE extname = 'pg_cron'
          ) THEN
            PERFORM cron.unschedule(jobid)
            FROM cron.job
            WHERE jobname = 'cleanup-ig-scrape-jobs';
          END IF;
        END
        $$;
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_private_ig_profile_snapshots_profile_id",
        table_name="ig_profile_snapshots",
        schema="private",
    )
    op.drop_index(
        "idx_ig_profile_snapshots_profile_scraped_at",
        table_name="ig_profile_snapshots",
        schema="private",
    )
    op.drop_table("ig_profile_snapshots", schema="private")
    op.drop_index(
        "ix_private_ig_scrape_jobs_status",
        table_name="ig_scrape_jobs",
        schema="private",
    )
    op.drop_index(
        "ix_private_ig_scrape_jobs_owner_user_id",
        table_name="ig_scrape_jobs",
        schema="private",
    )
    op.drop_index(
        "idx_ig_scrape_jobs_status_created_at",
        table_name="ig_scrape_jobs",
        schema="private",
    )
    op.drop_index(
        "idx_ig_scrape_jobs_owner_created_at",
        table_name="ig_scrape_jobs",
        schema="private",
    )
    op.drop_index(
        "idx_ig_scrape_jobs_expires_at",
        table_name="ig_scrape_jobs",
        schema="private",
    )
    op.drop_table("ig_scrape_jobs", schema="private")
    op.drop_index(
        "ix_private_ig_reels_documents_profile_id",
        table_name="ig_reels_documents",
        schema="private",
    )
    op.drop_index(
        "idx_ig_reels_documents_profile_updated_at",
        table_name="ig_reels_documents",
        schema="private",
    )
    op.drop_table("ig_reels_documents", schema="private")
    op.drop_index(
        "ix_private_ig_posts_documents_profile_id",
        table_name="ig_posts_documents",
        schema="private",
    )
    op.drop_index(
        "idx_ig_posts_documents_profile_updated_at",
        table_name="ig_posts_documents",
        schema="private",
    )
    op.drop_table("ig_posts_documents", schema="private")
    op.drop_index(
        "ix_private_ig_profiles_username",
        table_name="ig_profiles",
        schema="private",
    )
    op.drop_index(
        "ix_private_ig_profiles_ig_id",
        table_name="ig_profiles",
        schema="private",
    )
    op.drop_table("ig_profiles", schema="private")
    op.drop_table("ig_metrics", schema="private")
    op.drop_index(
        "ix_private_ig_credentials_login_username",
        table_name="ig_credentials",
        schema="private",
    )
    op.drop_table("ig_credentials", schema="private")
    # ### end Alembic commands ###
