/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingListRouteImport } from './routes/waiting-list'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookieTablesRouteImport } from './routes/cookie-tables'
import { Route as CookieNoticeRouteImport } from './routes/cookie-notice'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOverviewRouteImport } from './routes/_layout/overview'
import { Route as LayoutCreatorsSearchRouteImport } from './routes/_layout/creators-search'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutBrandIntelligenceRouteRouteImport } from './routes/_layout/brand-intelligence/route'
import { Route as LayoutBrandIntelligenceIndexRouteImport } from './routes/_layout/brand-intelligence/index'
import { Route as LayoutBrandIntelligenceReputationStrategyRouteImport } from './routes/_layout/brand-intelligence/reputation-strategy'

const WaitingListRoute = WaitingListRouteImport.update({
  id: '/waiting-list',
  path: '/waiting-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieTablesRoute = CookieTablesRouteImport.update({
  id: '/cookie-tables',
  path: '/cookie-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieNoticeRoute = CookieNoticeRouteImport.update({
  id: '/cookie-notice',
  path: '/cookie-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOverviewRoute = LayoutOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreatorsSearchRoute = LayoutCreatorsSearchRouteImport.update({
  id: '/creators-search',
  path: '/creators-search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrandIntelligenceRouteRoute =
  LayoutBrandIntelligenceRouteRouteImport.update({
    id: '/brand-intelligence',
    path: '/brand-intelligence',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutBrandIntelligenceIndexRoute =
  LayoutBrandIntelligenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutBrandIntelligenceRouteRoute,
  } as any)
const LayoutBrandIntelligenceReputationStrategyRoute =
  LayoutBrandIntelligenceReputationStrategyRouteImport.update({
    id: '/reputation-strategy',
    path: '/reputation-strategy',
    getParentRoute: () => LayoutBrandIntelligenceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cookie-notice': typeof CookieNoticeRoute
  '/cookie-tables': typeof CookieTablesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/waiting-list': typeof WaitingListRoute
  '/brand-intelligence': typeof LayoutBrandIntelligenceRouteRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/creators-search': typeof LayoutCreatorsSearchRoute
  '/overview': typeof LayoutOverviewRoute
  '/settings': typeof LayoutSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/brand-intelligence/reputation-strategy': typeof LayoutBrandIntelligenceReputationStrategyRoute
  '/brand-intelligence/': typeof LayoutBrandIntelligenceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/cookie-notice': typeof CookieNoticeRoute
  '/cookie-tables': typeof CookieTablesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/waiting-list': typeof WaitingListRoute
  '/admin': typeof LayoutAdminRoute
  '/creators-search': typeof LayoutCreatorsSearchRoute
  '/overview': typeof LayoutOverviewRoute
  '/settings': typeof LayoutSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/brand-intelligence/reputation-strategy': typeof LayoutBrandIntelligenceReputationStrategyRoute
  '/brand-intelligence': typeof LayoutBrandIntelligenceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/blog': typeof BlogRouteWithChildren
  '/cookie-notice': typeof CookieNoticeRoute
  '/cookie-tables': typeof CookieTablesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/waiting-list': typeof WaitingListRoute
  '/_layout/brand-intelligence': typeof LayoutBrandIntelligenceRouteRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/creators-search': typeof LayoutCreatorsSearchRoute
  '/_layout/overview': typeof LayoutOverviewRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_layout/brand-intelligence/reputation-strategy': typeof LayoutBrandIntelligenceReputationStrategyRoute
  '/_layout/brand-intelligence/': typeof LayoutBrandIntelligenceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/blog'
    | '/cookie-notice'
    | '/cookie-tables'
    | '/login'
    | '/privacy'
    | '/providers'
    | '/recover-password'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms-conditions'
    | '/waiting-list'
    | '/brand-intelligence'
    | '/admin'
    | '/creators-search'
    | '/overview'
    | '/settings'
    | '/blog/$slug'
    | '/blog/'
    | '/brand-intelligence/reputation-strategy'
    | '/brand-intelligence/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/cookie-notice'
    | '/cookie-tables'
    | '/login'
    | '/privacy'
    | '/providers'
    | '/recover-password'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms-conditions'
    | '/waiting-list'
    | '/admin'
    | '/creators-search'
    | '/overview'
    | '/settings'
    | '/blog/$slug'
    | '/blog'
    | '/brand-intelligence/reputation-strategy'
    | '/brand-intelligence'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about-us'
    | '/blog'
    | '/cookie-notice'
    | '/cookie-tables'
    | '/login'
    | '/privacy'
    | '/providers'
    | '/recover-password'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms-conditions'
    | '/waiting-list'
    | '/_layout/brand-intelligence'
    | '/_layout/admin'
    | '/_layout/creators-search'
    | '/_layout/overview'
    | '/_layout/settings'
    | '/blog/$slug'
    | '/blog/'
    | '/_layout/brand-intelligence/reputation-strategy'
    | '/_layout/brand-intelligence/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  BlogRoute: typeof BlogRouteWithChildren
  CookieNoticeRoute: typeof CookieNoticeRoute
  CookieTablesRoute: typeof CookieTablesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProvidersRoute: typeof ProvidersRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  WaitingListRoute: typeof WaitingListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-list': {
      id: '/waiting-list'
      path: '/waiting-list'
      fullPath: '/waiting-list'
      preLoaderRoute: typeof WaitingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-tables': {
      id: '/cookie-tables'
      path: '/cookie-tables'
      fullPath: '/cookie-tables'
      preLoaderRoute: typeof CookieTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-notice': {
      id: '/cookie-notice'
      path: '/cookie-notice'
      fullPath: '/cookie-notice'
      preLoaderRoute: typeof CookieNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/overview': {
      id: '/_layout/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof LayoutOverviewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/creators-search': {
      id: '/_layout/creators-search'
      path: '/creators-search'
      fullPath: '/creators-search'
      preLoaderRoute: typeof LayoutCreatorsSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brand-intelligence': {
      id: '/_layout/brand-intelligence'
      path: '/brand-intelligence'
      fullPath: '/brand-intelligence'
      preLoaderRoute: typeof LayoutBrandIntelligenceRouteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brand-intelligence/': {
      id: '/_layout/brand-intelligence/'
      path: '/'
      fullPath: '/brand-intelligence/'
      preLoaderRoute: typeof LayoutBrandIntelligenceIndexRouteImport
      parentRoute: typeof LayoutBrandIntelligenceRouteRoute
    }
    '/_layout/brand-intelligence/reputation-strategy': {
      id: '/_layout/brand-intelligence/reputation-strategy'
      path: '/reputation-strategy'
      fullPath: '/brand-intelligence/reputation-strategy'
      preLoaderRoute: typeof LayoutBrandIntelligenceReputationStrategyRouteImport
      parentRoute: typeof LayoutBrandIntelligenceRouteRoute
    }
  }
}

interface LayoutBrandIntelligenceRouteRouteChildren {
  LayoutBrandIntelligenceReputationStrategyRoute: typeof LayoutBrandIntelligenceReputationStrategyRoute
  LayoutBrandIntelligenceIndexRoute: typeof LayoutBrandIntelligenceIndexRoute
}

const LayoutBrandIntelligenceRouteRouteChildren: LayoutBrandIntelligenceRouteRouteChildren =
  {
    LayoutBrandIntelligenceReputationStrategyRoute:
      LayoutBrandIntelligenceReputationStrategyRoute,
    LayoutBrandIntelligenceIndexRoute: LayoutBrandIntelligenceIndexRoute,
  }

const LayoutBrandIntelligenceRouteRouteWithChildren =
  LayoutBrandIntelligenceRouteRoute._addFileChildren(
    LayoutBrandIntelligenceRouteRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutBrandIntelligenceRouteRoute: typeof LayoutBrandIntelligenceRouteRouteWithChildren
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCreatorsSearchRoute: typeof LayoutCreatorsSearchRoute
  LayoutOverviewRoute: typeof LayoutOverviewRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutBrandIntelligenceRouteRoute:
    LayoutBrandIntelligenceRouteRouteWithChildren,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCreatorsSearchRoute: LayoutCreatorsSearchRoute,
  LayoutOverviewRoute: LayoutOverviewRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  BlogRoute: BlogRouteWithChildren,
  CookieNoticeRoute: CookieNoticeRoute,
  CookieTablesRoute: CookieTablesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProvidersRoute: ProvidersRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  WaitingListRoute: WaitingListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
