/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitingListRouteImport } from './routes/waiting-list'
import { Route as TermsConditionsRouteImport } from './routes/terms-conditions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookieTablesRouteImport } from './routes/cookie-tables'
import { Route as CookieNoticeRouteImport } from './routes/cookie-notice'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMiningRouteImport } from './routes/_layout/mining'
import { Route as LayoutCreatorsSearchRouteImport } from './routes/_layout/creators-search'
import { Route as LayoutBrandIntelligenceRouteImport } from './routes/_layout/brand-intelligence'
import { Route as LayoutAppRouteImport } from './routes/_layout/app'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const WaitingListRoute = WaitingListRouteImport.update({
  id: '/waiting-list',
  path: '/waiting-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsConditionsRoute = TermsConditionsRouteImport.update({
  id: '/terms-conditions',
  path: '/terms-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieTablesRoute = CookieTablesRouteImport.update({
  id: '/cookie-tables',
  path: '/cookie-tables',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieNoticeRoute = CookieNoticeRouteImport.update({
  id: '/cookie-notice',
  path: '/cookie-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMiningRoute = LayoutMiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreatorsSearchRoute = LayoutCreatorsSearchRouteImport.update({
  id: '/creators-search',
  path: '/creators-search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrandIntelligenceRoute = LayoutBrandIntelligenceRouteImport.update({
  id: '/brand-intelligence',
  path: '/brand-intelligence',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAppRoute = LayoutAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/cookie-notice': typeof CookieNoticeRoute
  '/cookie-tables': typeof CookieTablesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/waiting-list': typeof WaitingListRoute
  '/admin': typeof LayoutAdminRoute
  '/app': typeof LayoutAppRoute
  '/brand-intelligence': typeof LayoutBrandIntelligenceRoute
  '/creators-search': typeof LayoutCreatorsSearchRoute
  '/mining': typeof LayoutMiningRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/cookie-notice': typeof CookieNoticeRoute
  '/cookie-tables': typeof CookieTablesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/waiting-list': typeof WaitingListRoute
  '/admin': typeof LayoutAdminRoute
  '/app': typeof LayoutAppRoute
  '/brand-intelligence': typeof LayoutBrandIntelligenceRoute
  '/creators-search': typeof LayoutCreatorsSearchRoute
  '/mining': typeof LayoutMiningRoute
  '/settings': typeof LayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/cookie-notice': typeof CookieNoticeRoute
  '/cookie-tables': typeof CookieTablesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/terms-conditions': typeof TermsConditionsRoute
  '/waiting-list': typeof WaitingListRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/app': typeof LayoutAppRoute
  '/_layout/brand-intelligence': typeof LayoutBrandIntelligenceRoute
  '/_layout/creators-search': typeof LayoutCreatorsSearchRoute
  '/_layout/mining': typeof LayoutMiningRoute
  '/_layout/settings': typeof LayoutSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/cookie-notice'
    | '/cookie-tables'
    | '/login'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms-conditions'
    | '/waiting-list'
    | '/admin'
    | '/app'
    | '/brand-intelligence'
    | '/creators-search'
    | '/mining'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/cookie-notice'
    | '/cookie-tables'
    | '/login'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms-conditions'
    | '/waiting-list'
    | '/admin'
    | '/app'
    | '/brand-intelligence'
    | '/creators-search'
    | '/mining'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about-us'
    | '/cookie-notice'
    | '/cookie-tables'
    | '/login'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/security'
    | '/signup'
    | '/terms-conditions'
    | '/waiting-list'
    | '/_layout/admin'
    | '/_layout/app'
    | '/_layout/brand-intelligence'
    | '/_layout/creators-search'
    | '/_layout/mining'
    | '/_layout/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  CookieNoticeRoute: typeof CookieNoticeRoute
  CookieTablesRoute: typeof CookieTablesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  TermsConditionsRoute: typeof TermsConditionsRoute
  WaitingListRoute: typeof WaitingListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiting-list': {
      id: '/waiting-list'
      path: '/waiting-list'
      fullPath: '/waiting-list'
      preLoaderRoute: typeof WaitingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-conditions': {
      id: '/terms-conditions'
      path: '/terms-conditions'
      fullPath: '/terms-conditions'
      preLoaderRoute: typeof TermsConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-tables': {
      id: '/cookie-tables'
      path: '/cookie-tables'
      fullPath: '/cookie-tables'
      preLoaderRoute: typeof CookieTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-notice': {
      id: '/cookie-notice'
      path: '/cookie-notice'
      fullPath: '/cookie-notice'
      preLoaderRoute: typeof CookieNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mining': {
      id: '/_layout/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof LayoutMiningRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/creators-search': {
      id: '/_layout/creators-search'
      path: '/creators-search'
      fullPath: '/creators-search'
      preLoaderRoute: typeof LayoutCreatorsSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brand-intelligence': {
      id: '/_layout/brand-intelligence'
      path: '/brand-intelligence'
      fullPath: '/brand-intelligence'
      preLoaderRoute: typeof LayoutBrandIntelligenceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/app': {
      id: '/_layout/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof LayoutAppRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAppRoute: typeof LayoutAppRoute
  LayoutBrandIntelligenceRoute: typeof LayoutBrandIntelligenceRoute
  LayoutCreatorsSearchRoute: typeof LayoutCreatorsSearchRoute
  LayoutMiningRoute: typeof LayoutMiningRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAppRoute: LayoutAppRoute,
  LayoutBrandIntelligenceRoute: LayoutBrandIntelligenceRoute,
  LayoutCreatorsSearchRoute: LayoutCreatorsSearchRoute,
  LayoutMiningRoute: LayoutMiningRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  CookieNoticeRoute: CookieNoticeRoute,
  CookieTablesRoute: CookieTablesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  TermsConditionsRoute: TermsConditionsRoute,
  WaitingListRoute: WaitingListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
